---
title: "Functional Protein Protein Interaction layer"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
```


```{r}
library(dplyr)
library(RCy3)
library(igraph)
library(data.table)
library(stringr)

"%ni%" <- Negate("%in%")
```

# DATA

## Cluster 1 vs Cluster 2

```{r}
Diff_Prot_exp <- read.csv("Results/Proteo/Diff_Prot_exp.tsv", sep = "\t", check.names = F)

Diff_Prot_exp_filtered_Mut_vs_group_control <- dplyr::filter(Diff_Prot_exp, Mutations_of_interest_vs_Group_control_p.val < 0.1) 

PPI_base <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")

colnames(PPI_base) <- c("source", "target", "Annotation", "Direction", "Score")

PPI_filtered <- dplyr::filter(PPI_base, source %in% Diff_Prot_exp_filtered_Mut_vs_group_control$name & target %in% Diff_Prot_exp_filtered_Mut_vs_group_control$name)
```

```{r}
write.table(PPI_filtered, "Results/Proteo/fPPI_filtered_network.tsv", sep = "\t", row.names = F)
```

## mIDH1 vs mIDH2

```{r}
Diff_Prot_exp_mIDH1_vs_mIDH2 <- read.csv("../../Results/Proteo/Diff_sig_Prot_exp_IDH1_IDH2.tsv", sep = "\t", check.names = F)

PPI_base <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")

colnames(PPI_base) <- c("source", "target", "Annotation", "Direction", "Score")

PPI_filtered_mIDH1_vs_mIDH2 <- dplyr::filter(PPI_base, source %in% Diff_Prot_exp_mIDH1_vs_mIDH2$name | target %in% Diff_Prot_exp_mIDH1_vs_mIDH2$name)
```

```{r}
write.table(PPI_filtered_mIDH1_vs_mIDH2, "../../Results/Proteo/PPI_filtered_mIDH1_vs_mIDH2.tsv", 
            sep = "\t", row.names = F, quote = F)
```

