---
title: "Sampling Layer 4"
subtitle: "Layer 4"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

# Libraries

```{r, error=F, warning=F, echo=FALSE, include=F}
rm(DmIALite, DOLite, DOLiteTerm, HsIALite, MmIALite, RnIALite)

library(dplyr)
library(parallel)
library(ggplot2)

cores2use <- detectCores()
source("~/Core_scripts/msviper_functions.R")
```

```{r}
mIDHi_react_scores_GEM <- read.csv("~/GitHub/Thesis_paper/Datasets/mIDHi_react_scores_GEM.csv", check.names = F, row.names = 1)
colnames(mIDHi_react_scores_GEM) <- colnames(mIDHi_react_scores_GEM) %>%
  stringr::str_remove("X")
```

```{r}
Sampling_layer <- lapply(1:20, function(sampling){
  sample(colnames(mIDHi_react_scores_GEM), size = 15, replace = F) 
})

Reactions <- lapply(1:20, function(Pheno){
  mIDHi_react_scores_GEM[Sampling_layer[[Pheno]]]
})
```

```{r}
library(biomaRt)
Human_GEM <- read.csv("~/GitHub/Thesis_paper/Datasets/Human_GEM_2.csv")
```

```{r}
Metabolic_network <- read.table("~/GitHub/Thesis_paper/Datasets/Metabolic_network_clean.tsv",
                                sep = "\t", header = T)

From_reversible_equation_to_network <- function(Reactions_values, Reaction){
  In_reaction_values <- Reactions_values[stringr::str_detect(rownames(Reactions_values), paste0(Reaction$ID, "_pos")), ]
  if(nrow(In_reaction_values) ==0){
    In_reaction_values_zscore <- 0
    Out_reaction_values_zscore <- 0
  }else{
    In_reaction_values$mean <- rowMeans(In_reaction_values)
    In_reaction_values$sd <- matrixStats::rowVars(as.matrix(dplyr::select(In_reaction_values, -c("mean"))))
    In_reaction_values_zscore <- In_reaction_values$mean / In_reaction_values$sd
    
    Out_reaction_values <- Reactions_values[stringr::str_detect(rownames(Reactions_values), paste0(Reaction$ID, "_neg")), ]
    if(nrow(Out_reaction_values) ==0){
      Out_reaction_values_zscore <- 0
    }else{
      Out_reaction_values$mean <- rowMeans(Out_reaction_values)
      Out_reaction_values$sd <- matrixStats::rowVars(as.matrix(dplyr::select(Out_reaction_values, -c("mean"))))
      Out_reaction_values_zscore <- Out_reaction_values$mean / Out_reaction_values$sd
    }
  }
  
  equation <- Reaction$EQUATION
  in_metabolites <- stringr::str_split_i(equation, pattern = "<=>", 1) %>% 
    stringr::str_split(pattern = " \\+ ") %>% unlist %>% stringr::str_trim() %>% 
    sapply(function(test){
      first_element <- stringr::str_split_i(test, pattern = " ", 1)
      if(stringr::str_detect(first_element, "[a-z]")){
        test
      }else{
        coeff <- stringr::str_split(test, pattern = " ") %>% .[[1]] %>% length()
        if(coeff > 2){
          splitted <- stringr::str_split(test, pattern = " ") %>% unlist %>% .[2:coeff] %>% paste(collapse = "_")
          splitted
        }else{
          stringr::str_split_i(test, pattern = " ", coeff)
        }
      }
    }) %>% unname
  out_metabolites <- stringr::str_split_i(equation, pattern = "<=>", 2) %>% 
    stringr::str_split(pattern = " \\+ ") %>% unlist %>% stringr::str_trim()  %>% 
    sapply(function(test){
      first_element <- stringr::str_split_i(test, pattern = " ", 1)
      if(stringr::str_detect(first_element, "[a-z]")){
        test
      }else{
        coeff <- length(stringr::str_split(test, pattern = " ")[[1]])
        if(coeff > 2){
          splitted <- stringr::str_split(test, pattern = " ") %>% unlist %>% .[2:coeff] %>% paste(collapse = "_")
          splitted
        }else{
          stringr::str_split_i(test, pattern = " ", coeff)
        }
      }
    }) %>% unname %>% 
    ifelse(. == "", in_metabolites, .)
  
  
  in_reactions_data_frame <- lapply(in_metabolites, function(metabolite){
    data.frame("A" = metabolite, "B" = Reaction$ID, "weight" = In_reaction_values_zscore)
  }) %>% data.table::rbindlist()
  
  out_reaction_data_frame <- lapply(out_metabolites, function(metabolite){
    data.frame("A" = Reaction$ID, "B" = metabolite, "weight" = Out_reaction_values_zscore)
  }) %>% data.table::rbindlist()
  
  rbind(in_reactions_data_frame, out_reaction_data_frame)
}

From_irreversible_equation_to_network <- function(Reactions_values, Reaction){
  In_reaction_values <- Reactions_values[stringr::str_detect(rownames(Reactions_values), paste0(Reaction$ID, "_pos")), ]
  if(nrow(In_reaction_values) ==0){
    In_reaction_values_zscore <- 0
  }else{
    In_reaction_values$mean <- rowMeans(In_reaction_values)
    In_reaction_values$sd <- matrixStats::rowVars(as.matrix(dplyr::select(In_reaction_values, -c("mean"))))
    In_reaction_values_zscore <- In_reaction_values$mean / In_reaction_values$sd
  }
  equation <- Reaction$EQUATION
  in_metabolites <- stringr::str_split_i(equation, pattern = "=>", 1) %>% 
    stringr::str_split(pattern = " \\+ ") %>% unlist %>% stringr::str_trim() %>% 
    sapply(function(test){
      first_element <- stringr::str_split_i(test, pattern = " ", 1)
      if(stringr::str_detect(first_element, "[a-z]")){
        test
      }else{
        coeff <- length(stringr::str_split(test, pattern = " ")[[1]])
        if(coeff > 2){
          splitted <- stringr::str_split(test, pattern = " ") %>% unlist %>% .[2:coeff] %>% paste(collapse = "_")
          splitted
        }else{
          res <- stringr::str_split_i(test, pattern = " ", coeff)
          res
        }
      }
    }) %>% unname
  out_metabolites <- stringr::str_split_i(equation, pattern = "=>", 2) %>% 
    stringr::str_split(pattern = " \\+ ") %>% unlist %>% stringr::str_trim() %>% 
    sapply(function(test){
      if(stringr::str_detect(stringr::str_split_i(test, pattern = " ", 1), "[a-z]")){
        test
      }else{
        coeff <- length(stringr::str_split(test, pattern = " ")[[1]])
        if(coeff > 2){
          splitted <- stringr::str_split(test, pattern = " ") %>% unlist %>% .[2:coeff] %>% paste(collapse = "_")
          splitted
        }else{
          stringr::str_split_i(test, pattern = " ", coeff)
        }
      }
    }) %>% unname
  
  in_reactions_data_frame <- lapply(in_metabolites, function(metabolite){
    data.frame("A" = metabolite, "B" = Reaction$ID, "weight" = In_reaction_values_zscore)
  }) %>% data.table::rbindlist()
  
  out_reaction_data_frame <- lapply(out_metabolites, function(metabolite){
    data.frame("A" = Reaction$ID, "B" = metabolite, "weight" = In_reaction_values_zscore)
  }) %>% data.table::rbindlist()
  
  rbind(in_reactions_data_frame)
}

From_Pheno_reaction_values_to_metabolic_network <- function(Class, Network = Human_GEM){
  mclapply(1:nrow(Network), function(reaction){
    if(stringr::str_detect(Network[reaction, "EQUATION"], pattern = "<=>")){
      From_reversible_equation_to_network(Reactions[[Class]], Network[reaction, ])
    }else{
      From_irreversible_equation_to_network(Reactions[[Class]], Network[reaction, ])
    }
  }, mc.cores = cores2use) %>% data.table::rbindlist()
}
```


```{r}
Classes_networks <- lapply(1:20, function(Pheno){
  From_Pheno_reaction_values_to_metabolic_network(Pheno)
})
```

# Calculate edges weight

## Function

```{r}
Scale_edges_weight <- function(Network){
  w_no_inf <- Network$weight %>% .[. != Inf]
  zscore_IQR <- (quantile(na.omit(w_no_inf), 0.75) - quantile(na.omit(w_no_inf), 0.25)) * 1.5
  zscore_weight_max <- quantile(na.omit(w_no_inf), 0.75) + zscore_IQR
  w_min <- Network$weight %>% .[. != 0] %>% min
  res <- Network
  res$scaled_weight <- sapply(Network$weight, function(w){
    if(w > zscore_weight_max){
      1
    }else if(w == 0){
      0
    }else{
      log(w)/log(zscore_weight_max)
    }
  })
  res
}
```

```{r}
Classes_networks_scaled <- lapply(1:20, function(Class){
  Scale_edges_weight(Classes_networks[[Class]])
})
```

```{r}
Folder_mulilayer <- "~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Sampling/Layer_4/"

NULL_lapply <- lapply(1:20, function(Pheno){
  dir.create(paste0(Folder_mulilayer, Pheno, "/Layer_4"), showWarnings = F)
  Classes_networks_scaled[[Pheno]][,c(1,2,4)] %>%
    write.table(paste0(Folder_mulilayer, "/", Pheno, "_Reactions_weighted.tsv"),
              sep = "\t", quote = F, row.names = F)
})
rm(NULL_lapply)
```


```{r}
save.image("/media/alexis/DATA/Session/R_session/Thesis_paper_Rsessions/Multi_layer_phenolike/Layer_4_sampling.RData")

```








