---
title: "Analyse single layers"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

# Libraries

```{r, error=F, warning=F, echo=FALSE, include=F}
rm(DmIALite, DOLite, DOLiteTerm, HsIALite, MmIALite, RnIALite)

library(dplyr)
library(RCy3)
library(igraph)
library(data.table)
library(stringr)
library(clusterProfiler)
library(ggplot2)
library(ggraph)
library(RColorBrewer)
library(viridis)
library(parallel)

cores2use <- detectCores() - 2
```

# Function to transform GO into Enrichmap 

```{r}
From_GO_to_network <- function(GO_data){
  formatted_genelists <- mclapply(1:nrow(GO_data), function(gene_set){
    GO_data[gene_set,]$geneID %>%
      stringr::str_split(pattern = "\\/") %>%
      unlist %>%
      as.vector %>%
      unique
  }, mc.cores = cores2use)
  mclapply(1:(nrow(GO_data)-1), function(gene_set){
    B_start <- gene_set + 1
    lapply(B_start:nrow(GO_data), function(gene_set_B){
      noverlap <- intersect(formatted_genelists[[gene_set]], formatted_genelists[[gene_set_B]]) %>%
        length
      data.frame("A" = GO_data[gene_set, 3], "B" = GO_data[gene_set_B, 3], "nOverlap" = noverlap)
    }) %>%
      data.table::rbindlist()

    }, mc.cores = cores2use) %>%
    data.table::rbindlist() %>% dplyr::filter(nOverlap > 1)
}
```

## Flow analysis

```{r}
Comparisons_flow <- c("Clusters_analysis", "mIDH_analysis")

Go_networks_flow <- lapply(Comparisons_flow, function(Comparison){
  if(Comparison == "Clusters_analysis"){
    short_name_file <- "Clusters"
  }else{
    short_name_file <- "mIDH"
  }
  comparison_analysis <- lapply(c("up", "down"), function(Sens){
    path_file <- paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/", 
                        Comparison, "/Go_", Sens, "_", short_name_file, ".tsv")
    print(path_file)
    go_datatable <- read.table(path_file, sep = "\t", row.names = 1, header = T, quote = "")
    res <- From_GO_to_network(go_datatable)
    write.table(res, paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/", 
                        Comparison, "/Go_", Sens, "_", short_name_file, "_network.tsv"),
                sep = "\t", row.names = F, quote =F)
    res
  })
  names(comparison_analysis) <- c("up", "down")
  comparison_analysis
})
names(Go_networks_flow) <- Comparisons_flow
```



## Versatility analysis

```{r}
Comparisons <- c("Clusters", "mIDH")
Stats <- list.dirs(paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Versatility_analysis/Clusters/"), 
                   full.names = F, recursive = F)

GO_networks_Versatility <- lapply(Comparisons, function(Comparison){
  comparison_analysis <- lapply(Stats, function(Stat){
    dir.create(paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Versatility_analysis/Clusters/", Stat, "/GO_table/Networks"), showWarnings = F)
    type_of_analysis <- list.files(paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Versatility_analysis/Clusters/", Stat, "/GO_table/"))
    stat_analysis <- lapply(type_of_analysis, function(toa){
      message(paste(Comparison, Stat, toa, sep = " "))
      go_dataframe <- tryCatch(expr =
                                 read.table(paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Versatility_analysis/Clusters/", Stat, "/GO_table/", toa), 
                                            sep = "\t", header = T, quote = ""), error = function(e){
        NULL
      })
      if(!is.null(go_dataframe)){
        res <- From_GO_to_network(go_dataframe)
        write.table(res, paste0("../../Results/Multi_layer_pheno_like/New_regulon_40k/Versatility_analysis/Clusters/", Stat, "/GO_table/Networks/Network_", toa), 
                    sep = "\t", row.names = F, quote =F)
        res
      }else{
        NULL
      }
    })
    names(stat_analysis) <- type_of_analysis %>% stringr::str_remove(pattern = ".tsv")
    stat_analysis
  })
  names(comparison_analysis) <- Stats
  comparison_analysis
})
names(GO_networks_Versatility) <- Comparisons
```

# Cytoscape analysis

```{r}
From_network_to_Cytoscape_analysis <- function(path_file, title){
  network <- read.table(path_file, sep = "\t", header = T, quote = "")
  inetwork <- graph_from_data_frame(network)
  createNetworkFromIgraph(inetwork, title = title, collection = title)
  cmd_clustering <- paste('cluster mcl', 'attribute=', "nOverlap", sep = " ")
  commandsRun(cmd_clustering)
  cmd_analyse_net <- paste('analyzer', 'analyze', 'directed=', "F", sep = " ")
  commandsRun(cmd_analyse_net)
  defaults <- list(NODE_SHAPE="diamond",
                   NODE_SIZE=10,
                   EDGE_TRANSPARENCY=120,
                   NODE_LABEL_POSITION="c,c,c,0.00,0.00")
  nodeLabels <- mapVisualProperty(visual.prop = "node label", table.column = 'name', mapping.type = 'p')
  createVisualStyle(title, defaults, list(nodeLabels))
  setVisualStyle(title)
  max_ov <- network$nOverlap %>% max
  setEdgeColorMapping(table.column = "nOverlap", table.column.values = c(2, max_ov), colors = c("#FFFFFF", "#FF0000"),
                      style.name = title)
  setEdgeOpacityMapping(table.column = "nOverlap", table.column.values = c(2, max_ov), opacities = c(50, 200),
                      style.name = title)
  setEdgeLineWidthMapping(table.column = "nOverlap", table.column.values = c(2, max_ov), widths = c(1, 10),
                      style.name = title)
  Stress_values <- RCy3::getTableColumns("node", columns = "Stress") %>% max
  setNodeColorMapping(table.column = "Stress", style.name = title, table.column.values = c(0, Stress_values), colors = c("#FFFFFF", "#FF0000"))
  setNodeSizeMapping(table.column = "Stress", style.name = title, table.column.values = c(0, Stress_values), sizes = c(10, 100))
}
```

```{r}
From_network_to_Cytoscape_analysis("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/Clusters_analysis/Go_down_Clusters_network.tsv", "Clusters_down")

From_network_to_Cytoscape_analysis("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/Clusters_analysis/Go_up_Clusters_network.tsv", "Clusters_up")

From_network_to_Cytoscape_analysis("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/mIDH_analysis/Go_down_mIDH_network.tsv", "mIDH_down")

From_network_to_Cytoscape_analysis("../../Results/Multi_layer_pheno_like/New_regulon_40k/Flow_analysis/mIDH_analysis/Go_up_mIDH_network.tsv", "mIDH_up")
```

