---
title: "Making Phenotype multilayer network"
subtitle: "Layer 3"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

# Libraries

```{r, error=F, warning=F, echo=FALSE, include=F}
rm(DmIALite, DOLite, DOLiteTerm, HsIALite, MmIALite, RnIALite)

library(dplyr)
library(parallel)
library(ggplot2)

cores2Use <- detectCores()
```

```{r}
PPI_base <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")

Proteomics_data <- read.table("../../Datasets/Proteomic/mIDH_data.tsv", sep = "\t", check.names = F, header = T, row.names = 1)
```

```{r}
Pheno_classes <- data.frame("sample" = colnames(Proteomics_data), 
                            "mIDH" = ifelse(stringr::str_detect(colnames(Proteomics_data), "1_"), "mIDH1", "mIDH2"))

Samples_mIDH1 <- Pheno_classes %>% dplyr::filter(mIDH == "mIDH1") %>% .$sample
Samples_mIDH2 <- Pheno_classes %>% dplyr::filter(mIDH == "mIDH2") %>% .$sample
Samples_Clustering <- Pheno_classes %>% dplyr::filter(mIDH == "mIDH2" | mIDH == "mIDH1") %>% .$sample

List_Pheno <- list("mIDH1"=Samples_mIDH1, 
                   "mIDH2"=Samples_mIDH2,
                   "IDHwt"=Samples_Clustering)

Samples_Proteo <- lapply(names(List_Pheno), function(Pheno){
  Proteomics_data[List_Pheno[[Pheno]]]
})
names(Samples_Proteo) <- names(List_Pheno)
```

```{r}
Samples_Proteo_stats <- lapply(names(Samples_Proteo), function(Pheno){
  res <- Samples_Proteo[[Pheno]]
  res$mean <- rowMeans(res)
  res$sd <- matrixStats::rowVars(as.matrix(select(res, -c("mean"))))
  res$zscore <- res$mean / res$sd
  res
})
names(Samples_Proteo_stats) <- names(Samples_Proteo)
```

```{r}
plot(x = Samples_Proteo_stats[["mIDH1"]]$zscore, y = Samples_Proteo_stats[["mIDH2"]]$zscore)
```

# Calculate edge weight

## Functions

```{r}
Return_mean_value <- function(Feature, Node){
  if(Node %in% rownames(Feature)){
    Feature[Node, "zscore"] + 1
  }else{
    1
  }
}

Calculate_edges_weight <- function(Network, Features){
  sapply(1:nrow(Network), function(node){
    A <- Return_mean_value(Features, Network[node, "Gene1"])
    B <- Return_mean_value(Features, Network[node, "Gene2"])
    A*B
  })
}
```

```{r}
PPIs <- lapply(names(Samples_Proteo_stats), function(Pheno){
  res <- PPI_base
  res$weight <- Calculate_edges_weight(PPI_base, Samples_Proteo_stats[[Pheno]])
  res
})
names(PPIs) <- names(Samples_Proteo_stats)
```

```{r}
plot(x = PPIs[["mIDH1"]]$weight, y = PPIs[["mIDH2"]]$weight)
```

# Scale weight

```{r}
Log_scaling_weight <- function(Network){
  w <- Network$weight
  w <- sapply(w, function(we){
    if(we == 0){
      0
    }else{
      log10(we)
    }
  })
  max_log_w <- max(w)
  scaled_weight <- sapply(w, function(we) we / max_log_w)
  scaled_weight
}
```

```{r}
Scaled_PPI <- lapply(names(PPIs), function(Pheno){
  res <- PPIs[[Pheno]]
  res$Scaled_weight <- Log_scaling_weight(res)
  res$Gene1 <- stringr::str_replace_all(res$Gene1, pattern = " ", replacement = "_") %>% 
    stringr::str_replace_all(pattern = " ", replacement = "_") %>%
    stringr::str_replace_all(pattern = " ", replacement = "_")
  res$Gene2 <- stringr::str_replace_all(res$Gene2, pattern = " ", replacement = "_") %>% 
    stringr::str_replace_all(pattern = " ", replacement = "_") %>%
    stringr::str_replace_all(pattern = " ", replacement = "_")
  res
})
names(Scaled_PPI) <- names(PPIs)
```

```{r}
Top_weighted <- function(PPI, N_top){
  PPI <- PPI[order(PPI$Scaled_weight, decreasing = T),]
  PPI[1:N_top,]
}
```


```{r}

```

```{r}
# PPI_mIDH_filtered <- Top_weighted(PPI_mIDH, 25000)
# PPI_mIDH1_filtered <- Top_weighted(PPI_mIDH1, 25000)
# PPI_mIDH2_filtered <- Top_weighted(PPI_mIDH2, 25000)
```

```{r}
plot(density(Scaled_PPI[["mIDH1"]]$Scaled_weight[Scaled_PPI[["mIDH1"]]$Scaled_weight!=0]), main = "mIDH1")
plot(density(Scaled_PPI[["mIDH2"]]$Scaled_weight[Scaled_PPI[["mIDH2"]]$Scaled_weight!=0]), main = "mIDH2")
plot(density(Scaled_PPI[["IDHwt"]]$Scaled_weight[Scaled_PPI[["IDHwt"]]$Scaled_weight!=0]), main = "IDHwt")
```

```{r}
names(Scaled_PPI) <- c("mIDH1", "mIDH2", "IDHwt")
lapply(names(Scaled_PPI), function(Class){
  png(paste0("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_3/", Class, "_interaction_values.png"))
  p <- Scaled_PPI[[Class]]$Scaled_weight %>% .[.!=0] %>% density %>% plot(main = Class)
  dev.off()
  p
})
```


# Make PPI directed 

```{r}
Make_PPI_directed <- function(Network){
  mclapply(1:nrow(Network), function(interaction){
    dir <- Network[interaction, "Direction"]
    if(dir == "->" | dir == "-|"){
      data.frame("Gene1" = Network[interaction, "Gene1"],
                 "Gene2" = Network[interaction, "Gene2"], 
                 "weight" = Network[interaction, "Scaled_weight"])
    }else if(dir == "<-" | dir == "|-"){
      data.frame("Gene1" = Network[interaction, "Gene2"],
                 "Gene2" = Network[interaction, "Gene1"], 
                 "weight" = Network[interaction, "Scaled_weight"])
    }else{
      w_2 <- Network[interaction, "Scaled_weight"] / 2
      data.frame("Gene1" = c(Network[interaction, "Gene1"], Network[interaction, "Gene2"]),
                 "Gene2" = c(Network[interaction, "Gene2"], Network[interaction, "Gene1"]),
                 "weight" = c(w_2, w_2)
                 )
    }
  }, mc.cores = cores2Use) %>% data.table::rbindlist() %>% unique
}
```

```{r}
Scaled_and_directed_PPI <- mclapply(names(Scaled_PPI), function(PPI){
  Make_PPI_directed(Scaled_PPI[[PPI]])
}, mc.cores = cores2Use)
names(Scaled_and_directed_PPI) <- names(Scaled_PPI)
```

```{r}
lapply(names(Scaled_and_directed_PPI), function(Class){
  png(paste0("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_3/", Class, "_interaction_values.png"))
  p <- Scaled_and_directed_PPI[[Class]]$weight %>% density %>% plot(main = Class)
  dev.off()
  p
})
```


```{r}
Plotting_function <- function(A, B, title, xlabel, ylabel){
  a_weight <- (A$weight > 0 & !is.nan(A$weight))
  b_weight <- (B$weight > 0 & !is.nan(B$weight))
  weight_test <- (a_weight & b_weight)
  a <- A[weight_test,]
  b <- B[weight_test,]
  df <- data.frame(x = a$weight, y = b$weight)
  d <- MASS::kde2d(df$x, df$y)
  dens <- data.frame(expand.grid(x = d$x, y = d$y), z = as.vector(d$z))
  plot_final <- ggplot() +
    geom_contour_filled(data = dens, aes(x=x, y=y, z =z, alpha = after_stat(level))) +
    theme(legend.position = "none") + xlab(xlabel) + ylab(ylabel)                  
  ggsave(paste0("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_3/", title, "_Cross_weight.png"), plot_final, 
         height = 2100, width = 2100, units = "px")
  plot_final
}
```


```{r}
Plotting_function(Scaled_and_directed_PPI$mIDH1, Scaled_and_directed_PPI$mIDH2, "mIDH1 vs mIDH2", "mIDH2", "mIDH1")
Plotting_function(Scaled_and_directed_PPI$mIDH1, Scaled_and_directed_PPI$IDHwt, "mIDH1 vs IDHwt", "mIDH1", "IDHwt")
Plotting_function(Scaled_and_directed_PPI$mIDH2, Scaled_and_directed_PPI$IDHwt, "mIDH2 vs IDHwt", "mIDH2", "IDHwt")
```


# Saving PPI

```{r}
Folder_Multilayer <- "~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Final_mutlilayer/"

lapply(names(Scaled_and_directed_PPI), function(Pheno){
  if(Pheno == "IDHwt"){
    dir.create(paste0(Folder_Multilayer, "R"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "R/Layer_3/"), showWarnings = F)

    dir.create(paste0(Folder_Multilayer, "NR"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "NR/Layer_3/"), showWarnings = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "R/Layer_3/PPI.tsv"), 
                         sep = "\t", row.names = F, quote = F)
    

    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "NR/Layer_3/PPI.tsv"), 
                         sep = "\t", row.names = F, quote = F)

    
  }else if(Pheno == "mIDH1"){
    dir.create(paste0(Folder_Multilayer, Pheno), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, Pheno, "/Layer_3/"), showWarnings = F)
    
    dir.create(paste0(Folder_Multilayer, "mIDH1_R"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "mIDH1_R", "/Layer_3/"), showWarnings = F)
    
    dir.create(paste0(Folder_Multilayer, "mIDH1_NR"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "mIDH1_NR", "/Layer_3/"), showWarnings = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, Pheno, "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "mIDH1_R", "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "mIDH1_NR", "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
    
  }else{
    dir.create(paste0(Folder_Multilayer, Pheno), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, Pheno, "/Layer_3/"), showWarnings = F)
    
    dir.create(paste0(Folder_Multilayer, "mIDH2_R"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "mIDH2_R/Layer_3/"), showWarnings = F)
    
    dir.create(paste0(Folder_Multilayer, "mIDH2_NR"), showWarnings = F)
    dir.create(paste0(Folder_Multilayer, "mIDH2_NR/Layer_3/"), showWarnings = F)
     
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, Pheno, "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "mIDH2_R", "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
    Scaled_and_directed_PPI[[Pheno]] %>% write.table(paste0(Folder_Multilayer, "mIDH2_NR", "/Layer_3/PPI.tsv"), 
                           sep = "\t", row.names = F, quote = F)
    
  }
  return(NULL)
})

```

# Saving PPI filtered

```{r, eval = F}
NO_DATA <- lapply(names(Scaled_PPI), function(Pheno){
  dir.create(paste0(Folder_Multilayer, Pheno), showWarnings = F)
  dir.create(paste0(Folder_Multilayer, Pheno, "/Layer_3/"), showWarnings = F)
  
  Scaled_PPI[[Pheno]] %>% 
    Top_weighted(25000) %>%
    write.table(paste0(Folder_Multilayer, Pheno, "/Layer_3/PPI_filtered.tsv"), 
                         sep = "\t", row.names = F, quote = F)
})


```

```{r}
save.image("/media/alexis/DATA/Session/R_session/Thesis_paper_Rsessions/Multi_layer_phenolike/layer_3.RData")
system("bash ~/shutdown_o_clock.sh")
```

