---
title: "Making Phenotype multilayer network"
subtitle: "Layer 1"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

# Libraries

```{r, error=F, warning=F, echo=FALSE, include=F}
rm(DmIALite, DOLite, DOLiteTerm, HsIALite, MmIALite, RnIALite)

library(dplyr)
library(chaser)
library(parallel)
library(ggplot2)

cores2use <- detectCores() -2
```

# Load DATA

```{r}
Clinical_patient_data <- read.table("../../Datasets/Clinical_Koichi_data_isoform.tsv", sep = "\t", header = T)
Clinical_patient_data$Baseline_phenotype_2 <- sapply(Clinical_patient_data$Best_response, function(resp){
  switch(resp,
         "CR" = "Responder",
         "CRp" = "Responder",
         "CRi" = "Responder",
         "MLFS" = "Overall_Responder",
         "HI" = "Overall_Responder",
         "PR" = "Overall_Responder",
         "SD" = "Non_Responder",
         "PD" = "Non_Responder",
         "Not_assessed" = "Not_assessed",
         "NA" = "Control")
})
BMIQ <- readRDS("/media/alexis/DATA/Koichi_methylation_dat/BMIQ_norm_Koichi_samples.Rdata")
```

## Prepare BMIQ to chaser

```{r, eval = F}
Anno_EPIC <- read.table("/media/alexis/DATA/Illumina_manifest/infinium-methylationepic.tsv", sep = "\t", header = T)
AnnoBMIQ <- merge(BMIQ, Anno_EPIC, by.x = 0, by.y = "Name")
AnnoBMIQ$end <- AnnoBMIQ$MAPINFO +1
AnnoBMIQ <- AnnoBMIQ %>% dplyr::select("MAPINFO":"end", "GSM4641437":"GSM4641541") 
colnames(AnnoBMIQ)[1:4] <- c("start", "strand", "chrom", "end")
AnnoBMIQ$chrom <- paste0("chr", AnnoBMIQ$chrom)
AnnoBMIQ <- AnnoBMIQ[,c(3,1,4:109)]
AnnoBMIQ$end <- as.integer(AnnoBMIQ$end)
write.table(AnnoBMIQ, "../../Datasets/Annotation_EPIC_BMIQ.tsv", sep = "\t", row.names = F)
```

```{r}
AnnoBMIQ <- read.table("../../Datasets/Annotation_EPIC_BMIQ.tsv", sep = "\t", header = T)
```


## Prepare Pheno

```{r}
Phenos <- colnames(AnnoBMIQ) %>% mclapply(function(sample){
  fil <- Clinical_patient_data %>%
    dplyr::filter(Baseline_Sample == sample) 
  data.frame("IDH" = fil$IDH_isoform, "Cluster" = fil$Cluster, 
             "sample" = fil$Baseline_Sample, "Response" = fil$Baseline_phenotype_2)
}, mc.cores = cores2use) %>% data.table::rbindlist()

AnnoBMIQ <- cbind(AnnoBMIQ[, 1:3], AnnoBMIQ[, colnames(AnnoBMIQ) %in% Phenos$sample])

# Samples_Cluster_IDH1_R <- Phenos %>% dplyr::filter(Cluster == "Cluster_R" & IDH == "IDH1") %>% .$sample
# Samples_Cluster_IDH2_R <- Phenos %>% dplyr::filter(Cluster == "Cluster_R" & (IDH == "IDH2_R140" | IDH == "IDH2_R172")) %>% .$sample
# Samples_Cluster_IDH2_NR <- Phenos %>% dplyr::filter(Cluster =="Cluster_NR"  & (IDH == "IDH2_R140" | IDH == "IDH2_R172")) %>% .$sample
Samples_mIDH1_R <- Phenos %>% dplyr::filter(Response == "Responder" & IDH == "IDH1") %>% .$sample
Samples_mIDH2_R <- Phenos %>% dplyr::filter(Response == "Responder" & (IDH == "IDH2_R140" | IDH == "IDH2_R172")) %>% .$sample
Samples_mIDH1_NR <- Phenos %>% dplyr::filter(Response == "Non_Responder" & IDH == "IDH1") %>% .$sample
Samples_mIDH2_NR <- Phenos %>% dplyr::filter(Response == "Non_Responder" & (IDH == "IDH2_R140" | IDH == "IDH2_R172")) %>% .$sample
# Samples_Double_NR <- Phenos %>% dplyr::filter(Response == "Non_Responder" & Cluster == "Cluster_NR") %>% .$sample
# Samples_NR_no_Cluster_NR <- Phenos %>% dplyr::filter(Response == "Non_Responder" & Cluster == "Cluster_R") %>% .$sample
# Samples_Double_R <- Phenos %>% dplyr::filter(Response == "Responder" & Cluster == "Cluster_R") %>% .$sample
# 
# Samples_Cluster_R <- Phenos %>% dplyr::filter(Cluster == "Cluster_R") %>% .$sample
# Samples_Cluster_NR <- Phenos %>% dplyr::filter(Cluster == "Cluster_NR") %>% .$sample
# Samples_R <- Phenos %>% dplyr::filter(Response == "Responder") %>% .$sample
# Samples_NR <- Phenos %>% dplyr::filter(Response == "Non_Responder") %>% .$sample
# Samples_mIDH1 <- Phenos %>% dplyr::filter(IDH == "IDH1") %>% .$sample
# Samples_mIDH2 <- Phenos %>% dplyr::filter(IDH == "IDH2_R140" | IDH == "IDH2_R172") %>% .$sample
# Samples_mIDH2_R172 <- Phenos %>% dplyr::filter(IDH == "IDH2_R172") %>% .$sample
# Samples_mIDH2_R140 <- Phenos %>% dplyr::filter(IDH == "IDH2_R140") %>% .$sample

Phenos_list <- list(
  # "R" = Samples_R, "NR" = Samples_NR,
                    # "Double_R" = Samples_Double_R, "Double_NR" = Samples_Double_NR,
                    # "Samples_NR_no_Cluster_NR" = Samples_NR_no_Cluster_NR,
                    # "mIDH1" = Samples_mIDH1, "mIDH2" = Samples_mIDH2,
                    # "mIDH2_R172" = Samples_mIDH2_R172, "mIDH2_R140" = Samples_mIDH2_R140,
                    # "Cluster_mIDH1_R" = Samples_Cluster_IDH1_R, "Cluster_mIDH2_R" = Samples_Cluster_IDH2_R,
                    # "Cluster_mIDH2_NR" = Samples_Cluster_IDH2_NR,
                    "mIDH1_R" = Samples_mIDH1_R, "mIDH2_R"= Samples_mIDH2_R,
                    "mIDH2_NR"= Samples_mIDH2_NR, "mIDH1_NR" = Samples_mIDH1_NR)

Anno_info <- AnnoBMIQ[, 1:3]

Annotations_samples <- lapply(names(Phenos_list), function(Pheno){
  cbind(Anno_info, AnnoBMIQ[, colnames(AnnoBMIQ) %in% Phenos_list[[Pheno]]])
})
names(Annotations_samples) <- names(Phenos_list)
```

## Prepare Pchic

### Function

```{r}
prepare_pchic <- function(cell_lines = NULL, minimum_interaction = 5, pchic = NULL){
  if (is.null(pchic)){
    load("/media/alexis/DATA/pchic.RData")
  }
  if (is.null(cell_lines)){
    cell_lines = c("Mon", "Mac0", "Mac1", "Mac2", "Neu", "MK", "EP", "Ery", "FoeT", "nCD4", "tCD4", "aCD4", "naCD4", "nCD8", "tCD8", "nB", "tB")
  }
  pchic <- data.frame(pchic[rowSums(pchic[,cell_lines] >= minimum_interaction) >= 1,c(1:3,5:8,10)]) %>% na.omit(.)
  pchic$baitChr <- paste0("chr", pchic$baitChr)
  pchic$oeChr <- paste0("chr", pchic$oeChr)
  return(pchic)
}
```

### Myeloid pchic

```{r}
Myelo_cell_lines <- c("Mon", "Mac1", "Mac0", "Mac2", "MK", "Ery", "EP")

pchic <- prepare_pchic(cell_lines = Myelo_cell_lines)
pchic_bed <- pchic
colnames(pchic_bed) <- rep(c("chr", "start", "end", "Name"), 2)
pchic_bed <- rbind(pchic_bed[,1:4], pchic_bed[,5:8]) %>%
  unique
rownames(pchic_bed) <- paste0(pchic_bed$chr, ":", pchic_bed$start, "-", pchic_bed$end)

po <- chaser::make_chromnet(pchic[,c(1:3, 5:7)])
```

```{r}
Pp_met <- mclapply(names(Annotations_samples), function(Pheno){
  chaser::load_features(po,Annotations_samples[[Pheno]],auxfun = 'mean', type='features_table',
                                           featnames = colnames(Annotations_samples[[Pheno]]), missingv=NA)
}, mc.cores = cores2use)
names(Pp_met) <- names(Annotations_samples)
```

```{r}
Pp_met_network <- Pp_met[["mIDH2"]]$edgesdf[, 7:8]

Pp_met_features <- mclapply(names(Pp_met), function(Pheno){
  Pp_met[[Pheno]][["features"]] %>% as.data.frame()
}, mc.cores = cores2use)
names(Pp_met_features) <- names(Pp_met)
```

```{r}
Pp_met_features <- mclapply(names(Pp_met_features), function(Pheno){
  tmp <- Pp_met_features[[Pheno]]
  tmp$mean <- rowMeans(tmp) 
  tmp
}, mc.cores = cores2use)
names(Pp_met_features) <- names(Pp_met)
```

# Save tables

```{r}
Folder_Multilayer <- "~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Final_mutlilayer/"

NO_DATA <- lapply(names(Pp_met_features), function(Pheno){
  dir.create(paste0(Folder_Multilayer, Pheno), showWarnings = F)
  dir.create(paste0(Folder_Multilayer, Pheno, "/Layer_1"), showWarnings = F)
  Pp_met_features[[Pheno]] %>%
      write.table(paste0(Folder_Multilayer, Pheno, "/Layer_1/Fragments_features.tsv"), 
                  sep = "\t", quote = F, row.names = T)
})
rm(NO_DATA)
```

```{r}
NO_DATA <- lapply(names(Pp_met_features), function(Pheno){
  d <- density(na.omit(Pp_met_features[[Pheno]]$mean))
  png(paste0("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/", Pheno, "_methylations_values.png"))
  plot(d, main = Pheno)
  dev.off()
  plot(d, main = Pheno)

})
rm(NO_DATA)
```

```{r}
Plotting_function <- function(A, B, title, xlabel, ylabel){
  a_weight <- (!is.na(A$mean))
  b_weight <- (!is.na(B$mean))
  weight_test <- (a_weight & b_weight)
  a <- A[weight_test,]
  b <- B[weight_test,]
  df <- data.frame(x = (a$mean), y = (b$mean))
  print(table(df$x > 0.6))
  print(table(df$y > 0.6))
  df <- dplyr::filter(df, (x < 0.6 | y < 0.6) & (abs(x - y) > 0.1))
  d <- MASS::kde2d(df$x, df$y)
  dens <- data.frame(expand.grid(x = d$x, y = d$y), z = as.vector(d$z))
  plot_final <- ggplot() +
    geom_contour_filled(data = dens, aes(x=x, y=y, z =z, alpha = after_stat(level))) +
    theme(legend.position = "none") + xlab(xlabel) + ylab(ylabel) +
    geom_vline(xintercept = 0.6, linetype="dashed") +
    geom_hline(yintercept = 0.6, linetype="dashed")
    ggsave(paste0("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/", title, "_Cross_weight.png"), plot_final, height = 2100, width = 2100, units = "px")
  plot_final
}
```

```{r}
Plotting_function(Pp_met_features[["mIDH1_NR"]], Pp_met_features[["mIDH1_R"]], "Response in IDH1", "mIDH1 Non responder", "mIDH1 Responder")
Plotting_function(Pp_met_features[["mIDH2_NR"]], Pp_met_features[["mIDH2_R"]], "Response in IDH2", "mIDH2 Non responder", "mIDH2 Responder")
Plotting_function(Pp_met_features[["mIDH2_R"]], Pp_met_features[["mIDH1_R"]], "IDH in Responder", "mIDH2 Responder", "mIDH1 Responder")
Plotting_function(Pp_met_features[["mIDH2_NR"]], Pp_met_features[["mIDH1_NR"]], "IDH in Non responder", "mIDH2 Non responder", "mIDH1 Non responder")
```



```{r}
plot(Pp_met_features[["mIDH1_R"]]$mean, Pp_met_features[["mIDH2_R"]]$mean, 
     main = "IDH in responder", xlab = "mIDH2 Responder", ylab = "mIDH1 Responder")
abline(h = 0.8)
abline(v = 0.8)
abline(0, 1)
```

```{r}
png("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/IDH_in_responder_methylations_values.png")
plot(Pp_met_features[["mIDH2_R"]]$mean, Pp_met_features[["mIDH1_R"]]$mean, 
     main = "IDH in responder", xlab = "mIDH2 Responder", ylab = "mIDH1 Responder")
dev.off()
```

```{r}
png("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/IDH_in_Non_responder_methylations_values.png")
plot(Pp_met_features[["mIDH2_NR"]]$mean, Pp_met_features[["mIDH1_NR"]]$mean, 
     main = "IDH in Non responder", xlab = "mIDH2 Non responder", ylab = "mIDH1 Non responder")
dev.off()
```

```{r}
png("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/Response_in_IDH1_methylations_values.png")
plot(Pp_met_features[["mIDH1_NR"]]$mean, Pp_met_features[["mIDH1_R"]]$mean, 
     main = "Response in IDH1", xlab = "mIDH1 Non responder", ylab = "mIDH1 Responder")
dev.off()
```

```{r}
png("~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/Layer_Figures/Layer_1/Response_in_IDH2_methylations_values.png")
plot(Pp_met_features[["mIDH2_NR"]]$mean, Pp_met_features[["mIDH2_R"]]$mean, 
     main = "Response in IDH2", xlab = "mIDH2 Non responder", ylab = "mIDH2 Responder")
dev.off()
```


# Associate chromatin fragments to genes

```{r,eval=F}
Associate_fragment_to_gene_promoter <- data.frame("source" = rownames(pchic_bed),
                                                  "target" = pchic_bed$Name) %>%
  dplyr::filter(target != ".") %>% 
  tidyr::separate_rows(target, sep = ";") %>%
  unique
Associate_fragment_to_gene_promoter %>% 
  write.table("../../Datasets/Chromatine_part/Associate_fragment_to_gene_promoter.tsv", 
              sep = "\t", quote = F, row.names = F)
```

# Calculate edges weight

## Functions

```{r}
Return_mean_value <- function(Feature, Node){
  if(Node %in% rownames(Feature)){
    Feature[Node, "mean"] > 0.6
  }else{
    F
  }
}

Calculate_edges_weight <- function(Network, Features){
  mclapply(1:nrow(Network), function(node){
    A <- Return_mean_value(Features, Network[node, "node_from"])
    B <- Return_mean_value(Features, Network[node, "node_to"])
    ifelse(A & B, 0, 1)
  }, mc.cores = cores2use) %>% unlist
}
```

## Calcul

```{r}
PP_Network <- lapply(names(Pp_met_features), function(Pheno){
  net <- Pp_met_network
  net$weight <- Calculate_edges_weight(net, select(Pp_met_features[[Pheno]], c("mean")))
  net
})
names(PP_Network) <- names(Pp_met_features)
```





```{r, eval = F}
save.image("/media/alexis/DATA/Session/R_session/Thesis_paper_Rsessions/Multi_layer_phenolike/Final_multi_layer_1_Response_analysis.RData")
# system("bash ~/shutdown_o_clock.sh")
```


## Filter methylated edges

```{r}
Filtered_network <- lapply(names(PP_Network), function(Pheno){
  net <- dplyr::filter(PP_Network[[Pheno]], weight==0 | is.na(weight))
  net$weight <- sapply(net$weight, function(w){
    ifelse(is.na(w), 0.2, 0.5)
  })
  net_back <- net[,c(2,1,3)]
  colnames(net_back) <- colnames(net)
  rbind(net, net_back)
})
names(Filtered_network) <- names(PP_Network)
```

```{r}
lapply(names(Filtered_network), function(Pheno){
  Filtered_network[[Pheno]] %>%
    write.table(paste0(Folder_Multilayer, Pheno, "/Layer_1/Network.tsv"), 
              sep = "\t", quote = F, row.names = F)
  NULL
})
```

```{r, eval = F}
Multi_folder <- "~/GitHub/Thesis_paper/Results/Multi_layer_pheno_like/"
NO_DATA <- lapply(names(Multi_layer), function(Class){
  net <- read.table(paste0(Multi_folder, Class, "/Layer_1/Network_base.tsv"), sep = "\t", header = T)
  net %>% write.table(paste0(Multi_folder, Class, "/Layer_1/Network_base.tsv"), 
              sep = "\t", quote = F, row.names = F)
  net$weight <- net$weight / 2
  net_back <- net[,c(2,1,3)]
  colnames(net_back) <- colnames(net)
  rbind(net, net_back) %>% write.table(paste0(Multi_folder, Class, "/Layer_1/Network.tsv"), 
              sep = "\t", quote = F, row.names = F)
})
rm(NO_DATA)
```



## Density plots

```{r}
lapply(names(Filtered_network), function(Pheno){
  plot(density(Filtered_network[[Pheno]]$weight, main = Pheno))
})
```

```{r}
save.image("/media/alexis/DATA/Session/R_session/Thesis_paper_Rsessions/Multi_layer_phenolike/Final_multi_layer_1.RData")
# system("bash ~/shutdown_o_clock.sh")
```

