---
title: "ATRA_treatment_anaylsis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---


```{r}
library(dplyr)
library(FactoMineR)
library(igraph)
library(limma)
library(viper)
library(stringr)
library(data.table)
library(RCy3)
library(factoextra)
library(pheatmap)
library(Hmisc)
library(matrixStats)
library(RColorBrewer)
library(pvca)
```

```{r}
Transcriptome_2HG_ATRA <- read.table("../Datasets/Transcriptome_2HG_ATRA.tsv", sep = "\t", row.names = 1, header = T, check.names = F)
Transcriptome_IDHm_ATRA <- read.table("../Datasets/Transcriptomes_ATRA_IDHm.tsv", sep = "\t", row.names = 1, header = T, check.names = F)
```

```{r}

Transcriptome_2HG_ATRA <- dplyr::filter(Transcriptome_2HG_ATRA, GnSymbol != "") %>% unique
Transcriptome_2HG_ATRA <- Transcriptome_2HG_ATRA[,c(2:13,1)]
Transcriptome_IDHm_ATRA <- dplyr::filter(Transcriptome_IDHm_ATRA, GnSymbol != "") %>% unique
Transcriptome_IDHm_ATRA <- Transcriptome_IDHm_ATRA[,c(2:15,1)]

```


```{r}
Combine_duplicated_gene_names_transcriptome <- function(transcriptome, colgenes){
  gene_list <- unique(transcriptome[,colgenes])
  transcriptome <- transcriptome %>%
    split(., .[colgenes]) %>%
    lapply(., function(x){
      l <- length(x[1,]) - 1
      cnames <- colnames(x)[c(1:l)]
      df <- x[,c(1:l)] %>%
        as.matrix(.) %>%
        colMaxs(.) %>% 
        data.frame(.) %>%
        t(.) %>%
        data.frame(.)
      colnames(df) <- cnames
      df
    }) %>%
    rbindlist(.) %>% 
    data.frame(., check.names = F)
  rownames(transcriptome) <- gene_list
  transcriptome
}
```

```{r}
Transcriptome_2HG_ATRA_combined <- Combine_duplicated_gene_names_transcriptome(Transcriptome_2HG_ATRA, "GnSymbol")

Transcriptome_IDHm_ATRA_combined <- Combine_duplicated_gene_names_transcriptome(Transcriptome_IDHm_ATRA, "GnSymbol")

```

```{r}
pheno_2HG_ATRA <- c(rep("HG2.CTRL", 3),rep("HG2.ATRA", 3),rep("Octyl.CTRL",3),rep("Octyl.ATRA",3))

res.pca <- prcomp(t(Transcriptome_2HG_ATRA_combined))
p <- fviz_pca_ind(res.pca, label="all", habillage=pheno_2HG_ATRA,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA gene expression")
p
png("../Results/DGEA/PCA_Transcriptome_2HG_ATRA_combined_data.png")
p
dev.off()
```

```{r}
pheno_2HG_ATRA <- c(rep("HG2.CTRL", 3),rep("HG2.ATRA", 3),rep("Octyl.CTRL",3),rep("Octyl.ATRA",3))

res.pca <- prcomp(t(Transcriptome_IDHm_ATRA_combined))
p <- fviz_pca_ind(res.pca, label="all", habillage=pheno_2HG_ATRA,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA gene expression")
p
png("../Results/DGEA/PCA_Transcriptome_2HG_ATRA_combined_data.png")
p
dev.off()
```

