---
title: "BEATAML_DNA_methylation_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
library(ChAMP)
require(minfi)  
require(BEclear)
require(factoextra)
require(zoo)
require(dplyr)

source("~/Core_scripts/core_functions.R")
```

```{r}
Clinical_BEATAML_data <- readxl::read_xlsx("../Datasets/beataml_wv1to4_clinical.xlsx", sheet = 1)
Convertisseur_BEATAML_1 <- readxl::read_xlsx("../Datasets/beataml_waves1to4_sample_mapping.xlsx", sheet = 1)
Convertisseur_BEATAML_2 <- read.table("../Datasets/Data_conversion.tsv", sep = "\t", header = F) %>% .[2:3]
Convertisseur_BEATAML_2$V3 <- Convertisseur_BEATAML_2$V3 %>%
  sapply(function(id){
    stringr::str_remove(id, "Beat AML project ") %>% stringr::str_remove_all("\\[|\\]")
  })
```

```{r}
Convertisseur_BEATAML <- merge(Convertisseur_BEATAML_1, Convertisseur_BEATAML_2, by.x = "labId", by.y = "V3", all.x = F, all.y = F)
Clinical_BEATAML_dnamethylation <- merge(Clinical_BEATAML_data, Convertisseur_BEATAML, by = "dbgap_subject_id", all.x = F, all.y = F)
```

```{r}
Clinical_BEATAML_dnamethylation_filtered <- Clinical_BEATAML_dnamethylation[c(107, 1:3, 9, 17:19, 35, 41:42, 50, 55:56, 63, 65:73, 86, 95:99, 102:103)]
test <- Clinical_BEATAML_dnamethylation_filtered$variantSummary %>% sapply(function(patient){
  tmp <- stringr::str_split(patient, "\\|") %>% c
  ifelse(stringr::str_detect(tmp, "IDH"), T, F)
})

Clinical_BEATAML_dnamethylation_filtered_IDHm <- Clinical_BEATAML_dnamethylation_filtered[test,] %>% .[!is.na(.$variantSummary),]
Clinical_BEATAML_dnamethylation_filtered_IDHm %>%
  write.table("../Datasets/Clinical_BEATAML_dnamethylation_filtered_IDHm.tsv", sep = "\t", row.names = F)

Clinical_BEATAML_dnamethylation_filtered_IDHm$V2 %>%
  write.table("../Datasets/IDHm_BEATAML_samples.tsv", sep = "\t", row.names = F, col.names = F, quote = F)
```

```{r}
Convertisseur_BEATAML_2 %>% 
  dplyr::filter(V2 %in% Clinical_BEATAML_dnamethylation_filtered_IDHm$V2)

Phenotypes_dnaseq <- read.table("/media/alexis/DATA/Thesis_paper_DATA/BEATAML_DNAmethylation/GSE159907_RAW/Phenotypes.csv", sep =",", header = T)

Phenotypes_dnaseq %>%
  dplyr::filter(Sample_Name %in% Clinical_BEATAML_dnamethylation_filtered_IDHm$V2) %>%
  write.table("/media/alexis/DATA/Thesis_paper_DATA/BEATAML_DNAmethylation/BEATAML_IDHm/Phenotypes.csv", sep = ",", row.names = F)
```

```{r}
RGSet <- read.metharray.exp(base = "/media/alexis/DATA/Thesis_paper_DATA/BEATAML_DNAmethylation/BEATAML_IDHm", recursive = T, force = TRUE)
RGSet <- convertArray(RGSet, outType = "IlluminaHumanMethylationEPIC")
# QC removes bad samples
# Samples with median Meth and Umneth signals below this cutoff will be labelled ‘bad’
MSet <- preprocessRaw(RGSet)
qc <- getQC(MSet)
plotQC(qc)
meds <- (qc$uMed + qc$mMed) / 2
keepIndex <- which(meds > 10.5)
Good_samples <- colnames(RGSet)[which(index(colnames(RGSet)) %in% keepIndex)]

Clinical_BEATAML_dnamethylation_filtered_IDHm$IDH1 <- sapply(Clinical_BEATAML_dnamethylation_filtered_IDHm$variantSummary, function(mutations){
  ifelse(stringr::str_detect(mutations, "IDH1"), "mIDH1", "wtIDH1")
})

Clinical_BEATAML_dnamethylation_filtered_IDHm$IDH2 <- sapply(Clinical_BEATAML_dnamethylation_filtered_IDHm$variantSummary, function(mutations){
  ifelse(stringr::str_detect(mutations, "IDH2"), "mIDH2", "wtIDH2")
})

Clinical_BEATAML_dnamethylation_filtered_IDHm$IDH <- paste(Clinical_BEATAML_dnamethylation_filtered_IDHm$IDH1, Clinical_BEATAML_dnamethylation_filtered_IDHm$IDH2, sep= "_") %>% stringr::str_remove(pattern = "wtIDH1_") %>% stringr::str_remove(pattern = "_wtIDH2")

RawBeta <- champ.load(directory = "/media/alexis/DATA/Thesis_paper_DATA/BEATAML_DNAmethylation/BEATAML_IDHm", arraytype = "EPIC")
Pheno_IDHm <- colnames(RawBeta$beta) %>% sapply(function(sample){
  Clinical_BEATAML_dnamethylation_filtered_IDHm %>% 
    dplyr::filter(V2 == sample) %>% .[1,] %>% .$IDH
})


champ.QC(beta = RawBeta$beta, pheno = Pheno_IDHm, resultsDir = "../Results/DNAmethylation/Rawbeta_QC")
```

```{r}
BMIQ <- champ.norm(beta = RawBeta$beta, arraytype = "EPIC", cores = 12, resultsDir = "../Results/DNAmethylation/BMIQ_Normalization/", method = "BMIQ")
gc()
```

```{r}
plot.beta.densities <- function(beta, title) {
  if (!is.null(dim(beta))) {
    densities <- apply(beta, 2, function(x) {
      density(x, na.rm = TRUE)
    })
    xmax <- max(sapply(densities, function(d) {
      max(d$x)
    }))
    xmin <- min(sapply(densities, function(d) {
      min(d$x)
    }))
    ymax <- max(sapply(densities, function(d) {
      max(d$y)
    }))

    plot(NA, xlim = c(xmin, xmax), ylim = c(0, ymax), main = title, ylab = "")
    colors <- rainbow(10)
    for (i in 1:ncol(beta)) {
      lines(densities[[i]], col = colors[i %% 10 + 1])
    }
  } else if (length(beta) > 1) {
    plot(density(beta, na.rm = TRUE), main = title)
  }
}
plot.beta.densities(RawBeta$beta, "Densities of raw values per sample")
plot.beta.densities(BMIQ, "Densities of BMIQ normalization per sample")
```

```{r}
library(sva)
library(Hmisc)
library(pheatmap)

cor_BMIQ <- rcorr(BMIQ, type = "pearson")$r
p <- pheatmap(cor_BMIQ, main = "Heatmap BMIQ")
p
ggsave("../Results/DNAmethylation/Heatmap_BEATAML.png", p)
```



```{r}
library(limma)
library(dplyr)
ct <- factor(Pheno_IDHm)
design <- model.matrix(~ 0 + ct)
colnames(design) <- levels(ct)
fit <- lmFit(BMIQ, design)
contrasts <- makeContrasts(mIDH2 - mIDH1, levels = design)
fit2 <- contrasts.fit(fit, contrasts)
fit2 <- eBayes(fit2, trend = TRUE)
summary(decideTests(fit2))


move <- function(data, cols, ref, side = c("before", "after")) {
  if (!requireNamespace("dplyr")) {
    stop("Make sure package 'dplyr' is installed to use function 'move'")
  }
  side <- match.arg(side)
  cols <- rlang::enquo(cols)
  ref <- rlang::enquo(ref)
  if (side == "before") {
    dplyr::select(data, 1:!!ref, -!!ref, -!!cols, !!cols, dplyr::everything())
  } else {
    dplyr::select(data, 1:!!ref, -!!cols, !!cols, dplyr::everything())
  }
}

FitList <- list()
for (i in 1:ncol(contrasts)) {
  FitList[[i]] <- topTable(fit2, coef = i, number = nrow(BMIQ)) %>%
    mutate(ID = rownames(.)) %>%
    move(., ID, logFC, side = "before") %>%
    filter(adj.P.Val < 0.05)
}
names(FitList) <- c("mIDH2 - mIDH1")

anno_epic <- read.csv("/media/alexis/DATA/Illumina_manifest/infinium-methylationepic-v-1-0-b5-manifest-file-csv/infinium-methylationepic-v-1-0-b5-manifest-file.csv", as.is = TRUE, skip = 7)
anno_epic <- anno_epic[, c("CHR", "MAPINFO", "Name", "UCSC_RefGene_Name")]


AnnoEpic <- move(anno_epic, Name, CHR, "before") %>% move(., UCSC_RefGene_Name, CHR, "before")

for (i in names(FitList)) {
  FitList[[i]] <- merge(AnnoEpic, FitList[[i]], by.x = "Name", by.y = "ID") %>%
    merge(., BMIQ, by.x = "Name", by.y = 0)
  rownames(FitList[[i]]) <- FitList[[i]]$Name
  FitList[[i]] <- FitList[[i]][, -1]
}

for (i in 1:length(FitList)) {
  names(FitList) <- colnames(summary(decideTests(fit2)))
  write.table(data.frame("CpGs" = rownames(FitList[[i]]), FitList[[i]]), file = paste(names(FitList)[i], ".txt"), sep = "\t", quote = F, row.names = F)
}
```

```{r}
dCPGs_BEATAML_IDHm <- Differential_analysis(Pheno_IDHm, BMIQ)

dCPGs_BEATAML_IDHm$`mIDH1-mIDH2` %>% write.table("../Results/DNAmethylation/dCPGs_IDHm_BEATAML.tsv", sep = "\t", row.names = T, col.names = NA)


DMP_mIDH <- champ.DMP(BMIQ, pheno = Pheno_IDHm, arraytype = "EPIC")
write.table(DMP_mIDH$mIDH2_to_mIDH1, "../Results/DNAmethylation/DMP_BEATAML_IDHm.tsv", sep = "\t", row.names = T, col.names = NA)
DMR_mIDH <- champ.DMR(as.matrix(BMIQ[,Pheno_IDHm != "mIDH1_mIDH2"]), pheno = Pheno_IDHm[Pheno_IDHm != "mIDH1_mIDH2"], arraytype = "EPIC", cores = 6)
write.table(DMR_mIDH$BumphunterDMR, "../Results/DNAmethylation/DMR_IDHm.tsv", sep = "\t", row.names = T, col.names = NA)
```


```{r}
GSEA_IDHm <- ChAMP::champ.GSEA(beta = BMIQ[,Pheno_IDHm != "mIDH1_mIDH2"], DMP = DMP_mIDH$mIDH2_to_mIDH1, DMR = DMR_mIDH, cores = 10, pheno = Pheno_IDHm[Pheno_IDHm != "mIDH1_mIDH2"], arraytype = "EPIC")
GSEA_IDHm$DMP %>% write.table("../Results/DNAmethylation/GSEA_DMP_IDHm.tsv", sep = "\t", row.names = F)
GSEA_IDHm$DMR %>% write.table("../Results/DNAmethylation/GSEA_DMR_IDHm.tsv", sep = "\t", row.names = F)

```

