---
title: "Chas_analysis_IDHs"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
```


```{r, echo = F, results='hide', warning=F, include=F}
library(dplyr)
library(chaser)
library(stringr)
library(biomaRt)
library(gridExtra)
library(grid)
library(ggplot2)
library(ggforce)
library(data.table)
library(factoextra)
library(RColorBrewer)
library(pheatmap)
library(Hmisc)
```

```{r}
source("~/Core_scripts/core_functions.R")
source("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Make_koichi_factor.R")
load("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/DATA/pchic.RData")
HSC_pchic <- read.table("../Datasets/HSC_Pchic_cleaned.tsv", sep = "\t", header = T)
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
```

```{r}
prepare_pchic <- function(cell_lines = NULL, minimum_interaction = 5, pchic = NULL){
  if (is.null(pchic)){
    load("DATA/pchic.RData")
  }
  if (is.null(cell_lines)){
    cell_lines = c("Mon", "Mac0", "Mac1", "Mac2", "Neu", "MK", "EP", "Ery", "FoeT", "nCD4", "tCD4", "aCD4", "naCD4", "nCD8", "tCD8", "nB", "tB")
  }
  pchic <- data.frame(pchic[rowSums(pchic[,cell_lines] >= minimum_interaction) >= 1,c(1,2,3,6,7,8)]) %>% na.omit(.)
  pchic$baitChr <- paste0("chr", pchic$baitChr)
  pchic$oeChr <- paste0("chr", pchic$oeChr)
  return(pchic)
}
```

```{r}
RNAseq_Koichi <- read.csv("~/GitHub/Koichi_gene_expression_analyses_git/Koichi_gene_expression_analyses/DATA/RNAseq_parsed.csv", row.names = 1, header = T, check.names = F)
Clinical_patient_data <- read.table("../Datasets/Clinical_Koichi_data.tsv", sep = "\t", header = T)
Phenotype_IDH_Koichi <- sapply(colnames(RNAseq_Koichi), function(sample){
  if(sample %in% Clinical_patient_data$Relapse_RNAseq_data){
    "Relapse"
  }else{
    Clinical_patient_data %>% dplyr::filter(Baseline_RNAseq_data == sample) %>% .$IDH_isoform
  }
})

RNAseq_Koichi_Baseline <- RNAseq_Koichi[Phenotype_IDH_Koichi != "Relapse"]
Phenotype_IDH_Koichi <- Phenotype_IDH_Koichi[Phenotype_IDH_Koichi != "Relapse"]
```

```{r}
RNAseqBEATAML <- read.table("/media/alexis/DATA/Thesis_paper_DATA/Voom_BEATAML.tsv", sep = "\t", header = T)
Pheno_BEATAML <- sapply(colnames(RNAseqBEATAML), function(samples){
  IDH1 <- stringr::str_detect(samples, pattern = "mIDH1")
  IDH2 <- stringr::str_detect(samples, pattern = "mIDH2")
  ifelse(IDH1, "mIDH1", ifelse(IDH2, "mIDH2", "wtIDH"))
})
RNAseqBEATAML <- RNAseqBEATAML[Pheno_BEATAML != "wtIDH"]
Pheno_BEATAML_IDH <- Pheno_BEATAML[Pheno_BEATAML != "wtIDH"]
```

```{r}
RNAseq_TCGA <- read.table("/media/alexis/DATA/Thesis_paper_DATA/Voom_TCGA.tsv", sep = "\t", header = T)
Pheno_TCGA <- sapply(colnames(RNAseq_TCGA), function(samples){
  IDH1 <- stringr::str_detect(samples, pattern = "mIDH1")
  IDH2 <- stringr::str_detect(samples, pattern = "mIDH2")
  ifelse(IDH1, "mIDH1", ifelse(IDH2, "mIDH2", "wtIDH"))
})

RNAseq_TCGA <- RNAseq_TCGA[Pheno_TCGA != "wtIDH"]
Pheno_TCGA_IDH <- Pheno_TCGA[Pheno_TCGA != "wtIDH"]
```

```{r}
Affy_Verhaak <- read.table("../Datasets/Verhaak_formated.tsv", sep = "\t", header = T, row.names = 1)
Verhaak_clinical_data <- read.table("../Datasets/Verhaak_Clinical_prepared.tsv", sep = "\t", header = T, row.names = 1)

Pheno_Verhaak_IDH <- sapply(colnames(Affy_Verhaak), function(samples){
  patient <- dplyr::filter(Verhaak_clinical_data, ID == samples)
  IDH1 <- ifelse(patient$IDH1 == 1, "mIDH1", "wtIDH1")
  IDH2 <- ifelse(patient$IDH2 == 1, "mIDH2", "wtIDH2")
  paste(IDH1, IDH2, sep = "_")
})

Affy_Verhaak_IDH <- Affy_Verhaak[Pheno_Verhaak_IDH != "wtIDH1_wtIDH2" & Pheno_Verhaak_IDH != "mIDH1_mIDH2"]
Pheno_Verhaak_IDH <- Pheno_Verhaak_IDH[Pheno_Verhaak_IDH != "wtIDH1_wtIDH2" & Pheno_Verhaak_IDH != "mIDH1_mIDH2"]

Patient_OS_summary <- summary(Verhaak_clinical_data$OS)
Pheno_Verhaak_OS <- sapply(colnames(Affy_Verhaak), function(samples){
  patient_OS <- dplyr::filter(Verhaak_clinical_data, ID == samples) %>% .$OS
  ifelse(patient_OS < Patient_OS_summary[2], "Low_OS", ifelse(patient_OS > Patient_OS_summary[5], "High_OS", "Overall_OS"))
})
```

```{r}
RNAseq_TUH <- read.table("../Datasets/RNASEQ_FULL_TABLE_SARRY.tsv", sep = "\t", header = T, row.names = 1) 
colnames(RNAseq_TUH) <- sapply(colnames(RNAseq_TUH), function(samples){
  stringr::str_split(samples, pattern = "_") %>% .[[1]] %>% .[1]
})
Pheno_TUH <- read.table("../Datasets/TUH_IDH_pheno.tsv", sep = "\t", header = F, col.names = c("id", "IDH", "Diff"))
Pheno_All_patients <- sapply(colnames(RNAseq_TUH), function(samples){
  if(samples %in% Pheno_TUH$id){
    dplyr::filter(Pheno_TUH, id == samples) %>% .$IDH
  }else{
    "wtIDH"
  }
})
RNAseq_TUH_mIDH <- RNAseq_TUH[Pheno_All_patients != "wtIDH"]
RNAseq_TUH_mIDH <- RNAseq_TUH_mIDH[,1:7]
Pheno_TUH_RNAseq <- dplyr::filter(Pheno_TUH, id %in% colnames(RNAseq_TUH_mIDH))
rownames(Pheno_TUH_RNAseq) <- Pheno_TUH_RNAseq$id
Pheno_TUH_RNAseq <- Pheno_TUH_RNAseq[colnames(RNAseq_TUH_mIDH),]
```

```{r}
Prepare_RNAseq_for_chaser <- function(RNAseq, title){
  gene_ensembl <- biomaRt::getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"), filters = "hgnc_symbol", values = rownames(RNAseq), mart = ensembl)
  gene_ensembl_2 <- gene_ensembl[!duplicated(gene_ensembl$hgnc_symbol) & gene_ensembl$hgnc_symbol != "CCL3L3" & !duplicated(gene_ensembl$ensembl_gene_id),]
  RNAseq_1_ensembl <- RNAseq[gene_ensembl_2$hgnc_symbol,]
  rownames(RNAseq_1_ensembl) <- gene_ensembl_2$ensembl_gene_id
  conv=read.delim(paste('/mnt/SERVER-CRCT-STORAGE/CRCT21/Private/common/forGARDEN-NET/biomart/','BLUEPRINT_fragments_good.tsv', sep='/'), sep='\t')
  convpro=data.frame(paste('chr',conv$chr, ':', conv$start, '-', conv$end, sep=''), conv$ensembl)
  rownames(convpro)=convpro[,1]
  colnames(convpro)[2]='ens.id'

  RNAseq_ENSEMBL_Coordinates <- merge(convpro, RNAseq_1_ensembl, by.x="ens.id", by.y = 0, all.x = F, all.y = F)
  colnames(RNAseq_ENSEMBL_Coordinates)[2] <- "coordinates"
  rownames(RNAseq_ENSEMBL_Coordinates) <- RNAseq_ENSEMBL_Coordinates$coordinates
  RNAseq_ENSEMBL_Coordinates<-RNAseq_ENSEMBL_Coordinates[,-c(1,2)]
  RNAseq_ENSEMBL_Coordinates <- data.frame(RNAseq_ENSEMBL_Coordinates, rowMeans(RNAseq_ENSEMBL_Coordinates), check.names = F)
  write.table(RNAseq_ENSEMBL_Coordinates, paste0("../Datasets/", title, "_RNAseq_ENSEMBL_Coordinates.tsv"), sep = "\t", row.names = T)
  RNAseq_ENSEMBL_Coordinates
}
```


```{r}
RNAseq_Koichi_4_Chaser <- Prepare_RNAseq_for_chaser(RNAseq_Koichi_Baseline, "KOICHI")
RNAseq_BEATAML_4_Chaser <- Prepare_RNAseq_for_chaser(RNAseqBEATAML, "BEATAML")
RNAseq_TCGA_4_Chaser <- Prepare_RNAseq_for_chaser(RNAseq_TCGA, "TCGA")
RNAseq_TUH_4_Chaser <- Prepare_RNAseq_for_chaser(RNAseq_TUH_mIDH, "TUH")
Affy_Verhaak_IDH_4_Chaser <- Prepare_RNAseq_for_chaser(Affy_Verhaak_IDH, "Verhaak")
Affy_Verhaak_4_Chaser <- Prepare_RNAseq_for_chaser(Affy_Verhaak, "Verhaak")
```

```{r, echo=F}
Myelo_cell_lines <- c("Mon", "Mac1", "Mac0", "Mac2", "MK", "Ery", "EP", "HSC")

pchics <- lapply(Myelo_cell_lines, function(cells){
  if(cells == "HSC"){
    ps <- HSC_pchic[,c(1:3,5:7)] %>% na.omit
    ps$bait_chr <- paste0("chr", ps$bait_chr)
    ps$otherEnd_chr <- paste0("chr", ps$otherEnd_chr)
  }else{
    ps <- prepare_pchic(cells, pchic = pchic)
  }
  po <- chaser::make_chromnet(ps)
  baits <- export(po, 'baits')
  chaser::subset_chromnet(po, method = "nodes", nodes1 = baits)
})
names(pchics) <- Myelo_cell_lines
```


```{r}
Make_chas_random <- function(RNAseq, pchic){
  chas_random <- lapply(names(pchics), function(cell_type){
    pp_exp <- chaser::load_features(pchics[[cell_type]],RNAseq,type='features_on_nodes',featnames = colnames(RNAseq), missingv=0)
    chas_random <- tryCatch(chaser::randomize(pp_exp, nrandom = 50, dist.match = T), error=function(e) NULL)
    lapply(chas_random, chas)
  })
  names(chas_random) <- c(Myelo_cell_lines, "HSC")
  chas_random
}
```

```{r, include = F, warning=F, echo = F}
BEATAML_Random_chas <- Make_chas_random(RNAseq_BEATAML_4_Chaser, pchics)
KOICHI_Random_chas <- Make_chas_random(RNAseq_Koichi_4_Chaser, pchics)
TCGA_Random_chas <- Make_chas_random(RNAseq_TCGA_4_Chaser, pchics)
TUH_Random_chas <- Make_chas_random(RNAseq_TUH_4_Chaser, pchics)
Verhaak_IDH_Random_chas <- Make_chas_random(Affy_Verhaak_IDH_4_Chaser, pchics)
Verhaak_Random_chas <- Make_chas_random(Affy_Verhaak_4_Chaser, pchics)
```

```{r}
# Rands_data_frame <- function(chas_random){
#   cells <- sapply(names(chas_random), function(cells){
#     length(chas_random[[cells]]) == 10
#   })
#   cells <- names(chas_random)[cells]
#   res <- lapply(cells, function(cell_line){
#     tmp <- unlist(chas_random[[cell_line]]) %>% unname
#     data.frame(cell_lines = rep(cell_line, length(tmp)), values = tmp)
#   }) %>% dplyr::bind_rows()
# }
# ```
# 
# ```{r}
# Rands_BEATAML <- Rands_data_frame(BEATAML_Random_chas)
# Rands_KOICHI <- Rands_data_frame(KOICHI_Random_chas)
# Rands_TCGA <- Rands_data_frame(TCGA_Random_chas)
# Rands_TUH <- Rands_data_frame(TUH_Random_chas)
# ```
# 
# ```{r}
# Chas_mean_sd <- function(Rands){
#   Chas_sd <- split(Rands, f = Rands$cell_lines)
#   Chas_sd <- sapply(Chas_sd, function(cell_line){
#     sd(cell_line$values)
#   }) %>% as.data.frame() %>% t()
#   
#   Chas_mean <- split(Rands, f = Rands$cell_lines)
#   Chas_mean <- sapply(Chas_mean, function(cell_line){
#     mean(cell_line$values)
#   }) %>% as.data.frame() %>% t()
#   list("MEAN" = Chas_mean, "SD" = Chas_sd)
# }
# ```
# 
# ```{r}
# Mean_SD_random_BEATAML <- Chas_mean_sd(Rands_BEATAML)
# Mean_SD_random_KOICHI <- Chas_mean_sd(Rands_KOICHI)
# Mean_SD_random_TCGA <- Chas_mean_sd(Rands_TCGA)
# Mean_SD_random_TUH <- Chas_mean_sd(Rands_TUH)
```


```{r}
chas_for_selected_pheno <- function(pchic = pchics, RNAseq, pheno, title, cells){
  RNAseq <- RNAseq[,pheno]
  
  pchics_pp <- lapply(cells, function(cell_type){
    message(cell_type)
    pp_exp <- chaser::load_features(pchics[[cell_type]],RNAseq,type='features_on_nodes',featnames = colnames(RNAseq), missingv=0)
    chas <- chaser::chas(pp_exp)
    feat <- chaser::export(pp_exp)
    list("pp_exp" = pp_exp, "chas" = chas, "feat" = feat)
  })
  names(pchics_pp) <- cells
  chas_cell_lines <- sapply(names(pchics_pp), function(cell_type){
    pchics_pp[[cell_type]][["chas"]]
  })
  message("Pchic_pp DONE!")
  chas_cell_lines_df <- data.frame(cell_lines = rep(cells, each = nrow(chas_cell_lines)),
                                   values = as.vector(chas_cell_lines),
                                   patient_id = rep(colnames(RNAseq), length(cells)))
  p <- ggplot2::ggplot(chas_cell_lines_df, aes(x = cell_lines, y = values, fill = cell_lines))
  p <- p + ggplot2::geom_boxplot()
  p <- p + theme(axis.line = element_line(colour = "black"),
                 axis.text.x=element_text(size=16),
                 axis.text.y=element_text(size=16),
                 axis.title.x=element_text(size=16),
                 axis.title.y=element_text(size=16))
  p <- p + ggplot2::geom_jitter()
  p <- p + ggtitle(title)

  list("plot" = p,
       "pchics_pp" = pchics_pp)
}
```

```{r}
Myelo_cell_lines <- c("Mon", "Mac1", "Mac0", "Mac2", "MK", "Ery", "EP")
# Myelo_cell_lines <- c("HSC")
```

```{r, include = F, warning=F, echo = F}
Pheno_BEATAML_IDH <- as.factor(Pheno_BEATAML_IDH)
Pheno_chas_BEATAML_Myeloid <- lapply(levels(Pheno_BEATAML_IDH), function(pheno){
  ref <- Pheno_BEATAML_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("BEATAML_", pheno), RNAseq = RNAseq_BEATAML_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_chas_BEATAML_Myeloid) <- levels(Pheno_BEATAML_IDH)
Pheno_chas_BEATAML_HSC <- lapply(levels(Pheno_BEATAML_IDH), function(pheno){
  ref <- Pheno_BEATAML_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("BEATAML_", pheno), RNAseq = RNAseq_BEATAML_4_Chaser, cells = c("HSC"))
})
names(Pheno_chas_BEATAML_HSC) <- levels(Pheno_BEATAML_IDH)
```

```{r, include = F, warning=F, echo = F}
Pheno_KOICHI_IDH <- as.factor(Phenotype_IDH_Koichi)
Pheno_chas_KOICHI_Myeloid <- lapply(levels(Pheno_KOICHI_IDH), function(pheno){
  ref <- Pheno_KOICHI_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("KOICHI_", pheno), RNAseq = RNAseq_Koichi_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_chas_KOICHI_Myeloid) <- levels(Pheno_KOICHI_IDH)

Pheno_chas_KOICHI_HSC <- lapply(levels(Pheno_KOICHI_IDH), function(pheno){
  ref <- Pheno_KOICHI_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("KOICHI_", pheno), RNAseq = RNAseq_Koichi_4_Chaser, cells = c("HSC"))
})
names(Pheno_chas_KOICHI_HSC) <- levels(Pheno_KOICHI_IDH)
```

```{r, include = F, warning=F, echo = F}
Pheno_TCGA_IDH <- as.factor(Pheno_TCGA_IDH)
Pheno_chas_TCGA_Myeloid <- lapply(levels(Pheno_TCGA_IDH), function(pheno){
  ref <- Pheno_TCGA_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("TCGA_", pheno), RNAseq = RNAseq_TCGA_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_chas_TCGA_Myeloid) <- levels(Pheno_TCGA_IDH)

Pheno_chas_TCGA_HSC <- lapply(levels(Pheno_TCGA_IDH), function(pheno){
  ref <- Pheno_TCGA_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("TCGA_", pheno), RNAseq = RNAseq_TCGA_4_Chaser, cells = c("HSC"))
})
names(Pheno_chas_TCGA_HSC) <- levels(Pheno_TCGA_IDH)
```

```{r, include = F, warning=F, echo = F}
Pheno_TUH_IDH <- as.factor(Pheno_TUH_RNAseq$IDH)
Pheno_chas_TUH_Myeloid <- lapply(levels(Pheno_TUH_IDH), function(pheno){
  ref <- Pheno_TUH_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("TUH_", pheno), RNAseq = RNAseq_TUH_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_chas_TUH_Myeloid) <- levels(Pheno_TUH_IDH)

Pheno_chas_TUH_HSC <- lapply(levels(Pheno_TUH_IDH), function(pheno){
  ref <- Pheno_TUH_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("TUH_", pheno), RNAseq = RNAseq_TUH_4_Chaser, cells = c("HSC"))
})
names(Pheno_chas_TUH_HSC) <- levels(Pheno_TUH_IDH)
```

```{r}
Pheno_Verhaak_IDH <- as.factor(Pheno_Verhaak_IDH)
Pheno_Verhaak_OS <- as.factor(Pheno_Verhaak_OS)
Pheno_IDH_chas_Verhaak_Myeloid <- lapply(levels(Pheno_Verhaak_IDH), function(pheno){
  ref <- Pheno_Verhaak_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("Verhaak_", pheno), RNAseq = Affy_Verhaak_IDH_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_IDH_chas_Verhaak_Myeloid) <- levels(Pheno_Verhaak_IDH)

Pheno_OS_chas_Verhaak_Myeloid <- lapply(levels(Pheno_Verhaak_OS), function(pheno){
  ref <- Pheno_Verhaak_OS == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("Verhaak_", pheno), RNAseq = Affy_Verhaak_4_Chaser, cells = Myelo_cell_lines)
})
names(Pheno_OS_chas_Verhaak_Myeloid) <- levels(Pheno_Verhaak_OS)

Pheno_IDH_chas_Verhaak_HSC <- lapply(levels(Pheno_Verhaak_IDH), function(pheno){
  ref <- Pheno_Verhaak_IDH == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("Verhaak_", pheno), RNAseq = Affy_Verhaak_IDH_4_Chaser, cells = c("HSC"))
})
names(Pheno_IDH_chas_Verhaak_HSC) <- levels(Pheno_Verhaak_IDH)

Pheno_OS_chas_Verhaak_HSC <- lapply(levels(Pheno_Verhaak_OS), function(pheno){
  ref <- Pheno_Verhaak_OS == pheno
  chas_for_selected_pheno(pheno = ref, title = paste0("Verhaak_", pheno), RNAseq = Affy_Verhaak_4_Chaser, cells = c("HSC"))
})
names(Pheno_OS_chas_Verhaak_HSC) <- levels(Pheno_Verhaak_OS)
```


```{r}
m1_HSC <- marrangeGrob(list(Pheno_chas_BEATAML_HSC$mIDH1$plot,
             Pheno_chas_KOICHI_HSC$IDH1$plot,
             Pheno_chas_BEATAML_HSC$mIDH2$plot,
             Pheno_chas_KOICHI_HSC$IDH2$plot,
             Pheno_chas_TCGA_HSC$mIDH1$plot,
             Pheno_chas_TUH_HSC$IDH1$plot,
             Pheno_chas_TCGA_HSC$mIDH2$plot,
             Pheno_chas_TUH_HSC$IDH2$plot,
             Pheno_IDH_chas_Verhaak_HSC$mIDH1_wtIDH2$plot,
             Pheno_OS_chas_Verhaak_HSC$High_OS$plot,
             Pheno_IDH_chas_Verhaak_HSC$wtIDH1_mIDH2$plot,
             Pheno_OS_chas_Verhaak_HSC$Low_OS$plot),
             ncol=2, nrow = 2)
m1_HSC
ggsave("../Results/Chromatine_part/Chas_GE_IDHm_all_HSC.pdf", m1_HSC)
m1_Myeloid <- marrangeGrob(list(Pheno_chas_BEATAML_Myeloid$mIDH1$plot,
             Pheno_chas_KOICHI_Myeloid$IDH1$plot,
             Pheno_chas_BEATAML_Myeloid$mIDH2$plot,
             Pheno_chas_KOICHI_Myeloid$IDH2$plot,
             Pheno_chas_TCGA_Myeloid$mIDH1$plot,
             Pheno_chas_TUH_Myeloid$IDH1$plot,
             Pheno_chas_TCGA_Myeloid$mIDH2$plot,
             Pheno_chas_TUH_Myeloid$IDH2$plot,
             Pheno_IDH_chas_Verhaak_Myeloid$mIDH1_wtIDH2$plot,
             Pheno_OS_chas_Verhaak_Myeloid$High_OS$plot,
             Pheno_IDH_chas_Verhaak_Myeloid$wtIDH1_mIDH2$plot,
             Pheno_OS_chas_Verhaak_Myeloid$Low_OS$plot),
             ncol=2, nrow = 2)
m1_Myeloid
ggsave("../Results/Chromatine_part/Chas_GE_IDHm_all_Myeloid.pdf", m1_Myeloid)
```

```{r}
Chas_zscore <- function(Chas, Random_distrib){
  chas_zscore <- lapply(names(Chas), function(comp){
    tmp <- Chas[[comp]][["plot"]][["data"]] %>% .[.$patient_id != "rowMeans(RNAseq_ENSEMBL_Coordinates)",]
    tmp <- split(tmp, tmp$cell_lines)
    l_rand <- sapply(names(Random_distrib), function(cell){
      length(Random_distrib[[cell]])
    })
    cell_lines <- names(Random_distrib) %>% .[l_rand != 0]
    cell_lines <- cell_lines[cell_lines %in% names(tmp)]
    n <- nrow(tmp[[cell_lines[1]]])
    message(paste0("cell lines to analysed: ", cell_lines, " on ", n, " patients"))
    zscores_list <- lapply(cell_lines, function(cell_line){
      message(cell_line)
      zscore <- sapply(tmp[[cell_line]]$patient_id, function(id){
        chas_rand <- sapply(1:length(Random_distrib[[cell_line]]), function(random){
          Random_distrib[[cell_line]][[random]][id]
        })
        rand_mean <- mean(chas_rand)
        rand_sd <- sd(chas_rand)
        chas_patient <- tmp[[cell_line]][tmp[[cell_line]]$patient_id == id,] %>% .$values
        zscores <- (chas_patient - rand_mean)/rand_sd
        zscores
      })
      zscore
    })
    names(zscores_list) <- cell_lines
    zscores <- sapply(zscores_list, function(cell_line){
      as.vector(cell_line)
    })
    res <- data.frame(cell_lines = rep(cell_lines, each = n),
                      zscore = as.vector(zscores),
                      patient_id = rep(tmp[[1]]$patient_id, length(cell_lines)))
  })
  names(chas_zscore) <- names(Chas)
  chas_zscore
}

```

```{r, echo=TRUE, include=T, warning=T}
BEATAML_Myeloid_zscores <- Chas_zscore(Pheno_chas_BEATAML_Myeloid, BEATAML_Random_chas)
BEATAML_HSC_zscores <- Chas_zscore(Pheno_chas_BEATAML_HSC, BEATAML_Random_chas)

KOICHI_Myeloid_zscores <- Chas_zscore(Pheno_chas_KOICHI_Myeloid, KOICHI_Random_chas)
KOICHI_HSC_zscores <- Chas_zscore(Pheno_chas_KOICHI_HSC, KOICHI_Random_chas)

TCGA_Myeloid_zscores <- Chas_zscore(Pheno_chas_TCGA_Myeloid, TCGA_Random_chas)
TCGA_HSC_zscores <- Chas_zscore(Pheno_chas_TCGA_HSC, TCGA_Random_chas)

TUH_Myeloid_zscores <- Chas_zscore(Pheno_chas_TUH_Myeloid, TUH_Random_chas)
TUH_HSC_zscores <- Chas_zscore(Pheno_chas_TUH_HSC, TUH_Random_chas)

Verhaak_IDH_Myeloid_zscores <- Chas_zscore(Pheno_IDH_chas_Verhaak_Myeloid, Verhaak_IDH_Random_chas)
Verhaak_IDH_HSC_zscores <- Chas_zscore(Pheno_IDH_chas_Verhaak_HSC, Verhaak_IDH_Random_chas)

Verhaak_OS_Myeloid_zscores <- Chas_zscore(Pheno_OS_chas_Verhaak_Myeloid, Verhaak_Random_chas)
Verhaak_OS_HSC_zscores <- Chas_zscore(Pheno_OS_chas_Verhaak_HSC, Verhaak_Random_chas)
```

```{r}
Chas_zscore_combined_plots <- function(Zscores, title){
  Zscores[[1]]$IDH <- rep(names(Zscores)[1], length(Zscores[[1]]$zscore))
  n_samples_1 <- length(unique(Zscores[[1]]$patient_id))
  n_samples_2 <- length(unique(Zscores[[2]]$patient_id))
  Zscores[[2]]$IDH <- rep(names(Zscores)[2], length(Zscores[[2]]$zscore))
  Zscores_combines <- rbind(Zscores[[1]], Zscores[[2]])
  title_final <- paste(title, "n=", n_samples_1, "&", "n=", n_samples_2)
  p <- ggplot2::ggplot(Zscores_combines, aes(x = cell_lines, y = zscore, fill = IDH))
  p <- p + ggplot2::geom_boxplot(outlier.shape = NA)
  p <- p + theme(axis.line = element_line(colour = "black"),
                 axis.text.x=element_text(size=16),
                 axis.text.y=element_text(size=16),
                 axis.title.x=element_text(size=16),
                 axis.title.y=element_text(size=16))
  p <- p + ggtitle(title_final)
  
  p
}

Max_zscores <- function(Zscores){
  zscores <- sapply(names(Zscores), function(IDH){
    Zscores[[IDH]]$zscore
  }) %>% c
  c(min(zscores), max(zscores))
}
```


```{r}
Chas_zscore_plots <- function(Zscores, title){
  res <- lapply(names(Zscores), function(IDH){
    n_samples <- length(unique(Zscores[[IDH]]$patient_id))
    p <- ggplot2::ggplot(Zscores[[IDH]], aes(x = cell_lines, y = zscore, fill = cell_lines)) 
    p <- p + ggplot2::geom_boxplot()
    p <- p + theme(axis.line = element_line(colour = "black"),
                   axis.text.x=element_text(size=16),
                   axis.text.y=element_text(size=16),
                   axis.title.x=element_text(size=16),
                   axis.title.y=element_text(size=16))
    p <- p + ggtitle(paste0(IDH, " ", title, " n=", n_samples))
    p
  })
  names(res) <- names(Zscores)
  res
}
```

```{r}
BEATAML_HSC_zscores_plot <- Chas_zscore_plots(BEATAML_HSC_zscores, "BEATAML")
BEATAML_HSC_zscores_plot
BEATAML_Myeloid_zscores_plot <- Chas_zscore_plots(BEATAML_Myeloid_zscores, "BEATAML")
BEATAML_Myeloid_zscores_plot

KOICHI_HSC_zscores_plot <- Chas_zscore_plots(KOICHI_HSC_zscores, "KOICHI")
KOICHI_HSC_zscores_plot
KOICHI_Myeloid_zscores_plot <- Chas_zscore_plots(KOICHI_Myeloid_zscores, "KOICHI")
KOICHI_Myeloid_zscores_plot

TCGA_HSC_zscores_plot <- Chas_zscore_plots(TCGA_HSC_zscores, "TCGA")
TCGA_HSC_zscores_plot
TCGA_Myeloid_zscores_plot <- Chas_zscore_plots(TCGA_Myeloid_zscores, "TCGA")
TCGA_Myeloid_zscores_plot

TUH_HSC_zscores_plot <- Chas_zscore_plots(TUH_HSC_zscores, "TUH")
TUH_HSC_zscores_plot
TUH_Myeloid_zscores_plot <- Chas_zscore_plots(TUH_Myeloid_zscores, "TUH")
TUH_Myeloid_zscores_plot
```

```{r}
m1_HSC <- marrangeGrob(list(BEATAML_HSC_zscores_plot$mIDH1,
                            KOICHI_HSC_zscores_plot$IDH1,
                            BEATAML_HSC_zscores_plot$mIDH2,
                            KOICHI_HSC_zscores_plot$IDH2,
                            TCGA_HSC_zscores_plot$mIDH1,
                            TUH_HSC_zscores_plot$IDH1,
                            TCGA_HSC_zscores_plot$mIDH2,
                            TUH_HSC_zscores_plot$IDH2),
             ncol=2, nrow = 2)
m1_HSC
ggsave("../Results/Chromatine_part/Chas_Zscore_GE_IDHm_HSC.pdf", m1_HSC)
m1_Myeloid <- marrangeGrob(list(BEATAML_Myeloid_zscores_plot$mIDH1,
                            KOICHI_Myeloid_zscores_plot$IDH1,
                            BEATAML_Myeloid_zscores_plot$mIDH2,
                            KOICHI_Myeloid_zscores_plot$IDH2,
                            TCGA_Myeloid_zscores_plot$mIDH1,
                            TUH_Myeloid_zscores_plot$IDH1,
                            TCGA_Myeloid_zscores_plot$mIDH2,
                            TUH_Myeloid_zscores_plot$IDH2),
             ncol=2, nrow = 2)
m1_Myeloid
ggsave("../Results/Chromatine_part/Chas_Zscore_GE_IDHm_all_Myeloid.pdf", m1_Myeloid)
```

```{r}
BEATAML_HSC_zscores_plot <- Chas_zscore_combined_plots(BEATAML_HSC_zscores, "BEATAML")
BEATAML_Myeloid_zscores_plot <- Chas_zscore_combined_plots(BEATAML_Myeloid_zscores, "BEATAML")
KOICHI_HSC_zscores_plot <- Chas_zscore_combined_plots(KOICHI_HSC_zscores, "KOICHI")
KOICHI_Myeloid_zscores_plot <- Chas_zscore_combined_plots(KOICHI_Myeloid_zscores, "KOICHI")
TCGA_HSC_zscores_plot <- Chas_zscore_combined_plots(TCGA_HSC_zscores, "TCGA")
TCGA_Myeloid_zscores_plot <- Chas_zscore_combined_plots(TCGA_Myeloid_zscores, "TCGA")
TUH_HSC_zscores_plot <- Chas_zscore_combined_plots(TUH_HSC_zscores, "TUH")
TUH_Myeloid_zscores_plot <- Chas_zscore_combined_plots(TUH_Myeloid_zscores, "TUH")
Verhaak_IDH_HSC_zscores_plot <- Chas_zscore_combined_plots(Verhaak_IDH_HSC_zscores, "Verhaak")
Verhaak_IDH_Myeloid_zscores_plot <- Chas_zscore_combined_plots(Verhaak_IDH_Myeloid_zscores, "Verhaak")
Verhaak_OS_HSC_zscores_plot <- Chas_zscore_combined_plots(Verhaak_OS_HSC_zscores, "Verhaak")
Verhaak_OS_Myeloid_zscores_plot <- Chas_zscore_combined_plots(Verhaak_OS_Myeloid_zscores, "Verhaak")
```

```{r}
m1_HSC <- marrangeGrob(list(BEATAML_HSC_zscores_plot,
                            KOICHI_HSC_zscores_plot,
                            TCGA_HSC_zscores_plot,
                            TUH_HSC_zscores_plot,
                            Verhaak_IDH_HSC_zscores_plot,
                            Verhaak_OS_HSC_zscores_plot),
                       ncol=2, nrow = 3)
m1_HSC
png1 <- grid.arrange(BEATAML_HSC_zscores_plot, KOICHI_HSC_zscores_plot, TCGA_HSC_zscores_plot, TUH_HSC_zscores_plot, Verhaak_IDH_HSC_zscores_plot,Verhaak_OS_HSC_zscores_plot,
             ncol=2,
             top = textGrob('Chas based on response',
                            just = c('center'),
                            gp = gpar(fontsize = 32)))
png1
ggsave("~/GitHub/Thesis_paper/Results/Chromatine_part/Chas_Zscore_GE_IDHm_HSC.pdf", m1_HSC)
ggsave("~/GitHub/Thesis_paper/Results/Chromatine_part/Chas_Zscore_GE_IDHm_HSC.png", png1)
m1_Myeloid <- marrangeGrob(list(BEATAML_Myeloid_zscores_plot,
                                KOICHI_Myeloid_zscores_plot,
                                TCGA_Myeloid_zscores_plot,
                                TUH_Myeloid_zscores_plot,
                                Verhaak_IDH_Myeloid_zscores_plot,
                                Verhaak_OS_Myeloid_zscores_plot),
                           ncol=2, nrow = 2)
m1_Myeloid
png2 <- grid.arrange(BEATAML_Myeloid_zscores_plot,
                     KOICHI_Myeloid_zscores_plot,
                     TCGA_Myeloid_zscores_plot,
                     TUH_Myeloid_zscores_plot,
                     Verhaak_IDH_Myeloid_zscores_plot,
                           ncol=2, nrow = 3, top = textGrob('Chas based on response',just = c('center'),gp = gpar(fontsize = 32)))
png2
ggsave("~/GitHub/Thesis_paper/Results/Chromatine_part/Chas_Zscore_GE_IDHm_all_Myeloid.pdf", m1_Myeloid)
ggsave("~/GitHub/Thesis_paper/Results/Chromatine_part/Chas_Zscore_GE_IDHm_all_Myeloid.png", png2)
```

