---
title: "Deconvolution analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
library(dplyr)
library(pheatmap)
library(matrixStats)
library(RColorBrewer)
library(ggplot2)

"%ni%" <- Negate("%in%")
wd <- "~/GitHub/Thesis_paper/"
```

```{r}
Prepare_TUH_deconvolution <- function(Pheno, deconvolution_data_filename, sep){
  deconvolution_df <- read.table(paste0("../Results/Deconvolution/", deconvolution_data_filename), sep = sep, header = T)
  deconvolution_df$Mixture <- sapply(deconvolution_df$Mixture, function(samples){
  stringr::str_split(samples, pattern = "_") %>% .[[1]] %>% .[1]
})
  deconvolution_df <- deconvolution_df[!duplicated(deconvolution_df$Mixture),]
  Pheno_All_patients <- sapply(deconvolution_df$Mixture, function(samples){
    if(samples %in% Pheno$id){
      dplyr::filter(Pheno, id == samples) %>% .$IDH
    }else{
      "wtIDH"
    }
  })
  deconvolution_df_IDH <- deconvolution_df[Pheno_All_patients != "wtIDH",]
  Pheno_All_patients <- merge(Pheno, Pheno_All_patients, by.x = "id", by.y = 0, all.x = T, all.y = T)
  Pheno_All_patients <- dplyr::filter(Pheno_All_patients, id %in% deconvolution_df$Mixture)
  Pheno_All_patients <- Pheno_All_patients[c(1,3,4)]
  Pheno_All_patients$Diff <- sapply(Pheno_All_patients$Diff, function(diff){
    if(is.na(diff)){
      "na"
    }else{
      diff
    }
  })
  colnames(Pheno_All_patients)[3] <- "IDH"
  Pheno_deconvolution <- dplyr::filter(Pheno, id %in% deconvolution_df_IDH$Mixture)
  rownames(Pheno_deconvolution) <- Pheno_deconvolution$id
  Pheno_deconvolution <- Pheno_deconvolution[deconvolution_df_IDH$Mixture,]
  list(Pheno_deconvolution = Pheno_deconvolution, deconvolution_df = deconvolution_df_IDH, all_deconvolution_data = deconvolution_df, Pheno_All_patients = Pheno_All_patients)
}
```

### TUH deconvolutions

```{r}
Pheno_TUH <- read.table("../Datasets/TUH_IDH_pheno.tsv", sep = "\t", header = F, col.names = c("id", "IDH", "Diff"))

TUH_JohnD_deconvolution <- Prepare_TUH_deconvolution(Pheno_TUH, deconvolution_data_filename = "CIBERSORTx_JohnD_Results.csv", ",")
TUH_BPRNACan3DProMet <- Prepare_TUH_deconvolution(Pheno_TUH, deconvolution_data_filename = "CIBERSORTx_BPRNA3DProMet_Results.csv", ",")
TUH_CBSX_sigmatrix_HNSCC <- Prepare_TUH_deconvolution(Pheno_TUH, deconvolution_data_filename = "CIBERSORTx_CBSX_sigmatrix_HNSCC_Fig2cd_Results.txt", "\t")
TUH_CCLE_TIL10 <- Prepare_TUH_deconvolution(Pheno_TUH, deconvolution_data_filename = "CIBERSORTx_CCLE_TIL10_Results.tsv", "\t")
order_JohnD_signatures <- colnames(TUH_JohnD_deconvolution$deconvolution_df)[c(1, 7, 5, 6, 12, 8, 4, 15, 9, 14, 2, 10, 13, 3, 11, 16:18)]
order_JohnD_signatures
TUH_JohnD_deconvolution$deconvolution_df <- TUH_JohnD_deconvolution$deconvolution_df[,order_JohnD_signatures]
TUH_JohnD_deconvolution$all_deconvolution_data <- TUH_JohnD_deconvolution$all_deconvolution_data[,order_JohnD_signatures]
```

```{r}
Make_TUH_deconvolution_annotated_heatmap <- function(deconvolution_df, Pheno, title){
  annotation_for_heatmap <- Pheno
  rownames(annotation_for_heatmap) <- annotation_for_heatmap$id
  annotation_for_heatmap <- annotation_for_heatmap %>% dplyr::select(-"id")
  ann_color <- list(
    IDH = c(IDH1 = "red",  IDH2= "darkred", wtIDH = "white"),
    Diff = c(CMP = "blue", GP = "brown", MP1 = "green", MPP = "orange", na = "grey")
    )
  ncolumn <- ncol(deconvolution_df)
  data4heatmap <- deconvolution_df[1:(ncolumn-3)]
  rownames(data4heatmap) <- data4heatmap$Mixture
  data4heatmap <- data4heatmap[-1]
  heatmap <- pheatmap(data4heatmap, 
                      color = rev(colorRampPalette(brewer.pal(n = 9, name = "RdBu"))(100)),
                      annotation_row = annotation_for_heatmap,
                      annotation_colors = ann_color,
                      legend = TRUE,
                      treeheight_row = 20,
                      main = title, 
                      fontsize = 10, scale = "row", show_rownames = F, cluster_cols=F
  )
  ggsave(paste0("../Results/Deconvolution/Heatmap_", title, ".png"), heatmap)
  return(heatmap)
}
```

```{r}
TUH_JohnD_deconvolution_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_JohnD_deconvolution$deconvolution_df, TUH_JohnD_deconvolution$Pheno_deconvolution, "TUH_deconvolution_JohnD")
TUH_BPRNACan3DProMet_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_BPRNACan3DProMet$deconvolution_df, TUH_BPRNACan3DProMet$Pheno_deconvolution,  "TUH_deconvolution_BPRNACan3DProMet")
TUH_CBSX_sigmatrix_HNSCC_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_CBSX_sigmatrix_HNSCC$deconvolution_df, TUH_CBSX_sigmatrix_HNSCC$Pheno_deconvolution, "TUH_deconvolution_CBSX_sigmatrix_HNSCC") 
TUH_CCLE_TIL10_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_CCLE_TIL10$deconvolution_df, TUH_CCLE_TIL10$Pheno_deconvolution, "TUH_deconvolution_CCLE_TIL10") 
```

```{r}
TUH_all_samples_JohnD_deconvolution_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_JohnD_deconvolution$all_deconvolution_data, TUH_JohnD_deconvolution$Pheno_All_patients, "TUH_all_samples_deconvolution_JohnD")

TUH_all_samples_BPRNACan3DProMet_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_BPRNACan3DProMet$all_deconvolution_data, TUH_BPRNACan3DProMet$Pheno_All_patients,  "TUH_all_samples_deconvolution_BPRNACan3DProMet")

TUH_all_samples_CBSX_sigmatrix_HNSCC_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_CBSX_sigmatrix_HNSCC$all_deconvolution_data, TUH_CBSX_sigmatrix_HNSCC$Pheno_All_patients, "TUH_all_samples_deconvolution_CBSX_sigmatrix_HNSCC") 

TUH_all_samples_CCLE_TIL10_heatmap <- Make_TUH_deconvolution_annotated_heatmap(TUH_CCLE_TIL10$all_deconvolution_data, TUH_CCLE_TIL10$Pheno_All_patients, "TUH_all_samples_deconvolution_CCLE_TIL10") 
```

### BEATAML Deconvolution

```{r}
Prepare_BEATAML_deconvolution <- function(deconvolution_data_filename, sep){
  deconvolution_df <- read.table(paste0("../Results/Deconvolution/", deconvolution_data_filename), sep = sep, header = T)
  Pheno_deconvolution <- sapply(deconvolution_df$Mixture, function(samples){
    substr(samples, 1, 5)
  })
  Pheno_deconvolution <- data.frame(id = names(Pheno_deconvolution),
                                    IDH = unname(Pheno_deconvolution))
  Pheno_deconvolution_IDH <- dplyr::filter(Pheno_deconvolution, IDH != "IDHwt")
  deconvolution_df_IDH <- dplyr::filter(deconvolution_df, Mixture %in% Pheno_deconvolution_IDH$id)
  list(Pheno_deconvolution = Pheno_deconvolution, deconvolution_df = deconvolution_df, Pheno_deconvolution_IDH = Pheno_deconvolution_IDH, deconvolution_df_IDH = deconvolution_df_IDH)
}
```

```{r}
BEATAML_JohnD_deconvolution <- Prepare_BEATAML_deconvolution(deconvolution_data_filename = "CIBERSORTx_JohnD_BEATAML_Results.tsv", "\t")
BEATAML_BPRNACAN3DProMet_deconvolution <- Prepare_BEATAML_deconvolution(deconvolution_data_filename = "CIBERSORTx_BPRNACAN3DProMet_BEATAML_Results.tsv", "\t")

BEATAML_JohnD_deconvolution$deconvolution_df_IDH <- BEATAML_JohnD_deconvolution$deconvolution_df_IDH[,order_JohnD_signatures]
BEATAML_JohnD_deconvolution$deconvolution_df <- BEATAML_JohnD_deconvolution$deconvolution_df[,order_JohnD_signatures]
```

```{r}
Make_BEATAML_deconvolution_annotated_heatmap <- function(deconvolution_df, Pheno, title){
  annotation_for_heatmap <- Pheno
  rownames(annotation_for_heatmap) <- annotation_for_heatmap$id
  annotation_for_heatmap <- annotation_for_heatmap %>% dplyr::select(-"id")
  ann_color <- list(
    IDH = c(mIDH1 = "red",  mIDH2= "darkred", IDHwt = "white")
    )
  ncolumn <- ncol(deconvolution_df)
  data4heatmap <- deconvolution_df[1:(ncolumn-3)]
  rownames(data4heatmap) <- data4heatmap$Mixture
  data4heatmap <- data4heatmap[-1]
  heatmap <- pheatmap(data4heatmap, 
                      color = rev(colorRampPalette(brewer.pal(n = 9, name = "RdBu"))(100)),
                      annotation_row = annotation_for_heatmap,
                      annotation_colors = ann_color,
                      legend = TRUE,
                      treeheight_row = 20,
                      main = title, 
                      fontsize = 10, scale = "row", show_rownames = F, cluster_cols = F
  )
  ggsave(paste0("../Results/Deconvolution/Heatmap_", title, ".png"), heatmap)
  return(heatmap)
}
```

```{r}
BEATAML_all_samples_JohnD_deconvolution_heatmap <- Make_BEATAML_deconvolution_annotated_heatmap(BEATAML_JohnD_deconvolution$deconvolution_df, BEATAML_JohnD_deconvolution$Pheno_deconvolution, "BEATAML_all_samples_deconvolution_JohnD")

BEATAML_mIDH_samples_JohnD_deconvolution_heatmap <- Make_BEATAML_deconvolution_annotated_heatmap(BEATAML_JohnD_deconvolution$deconvolution_df_IDH, BEATAML_JohnD_deconvolution$Pheno_deconvolution_IDH, "BEATAML_mIDH_samples_deconvolution_JohnD")

BEATAML_all_samples_BPRNACAN3DProMet_deconvolution_heatmap <- Make_BEATAML_deconvolution_annotated_heatmap(BEATAML_BPRNACAN3DProMet_deconvolution$deconvolution_df, BEATAML_BPRNACAN3DProMet_deconvolution$Pheno_deconvolution, "BEATAML_all_samples_deconvolution_BPRNACAN3DProMet")

BEATAML_mIDH_samples_BPRNACAN3DProMet_deconvolution_heatmap <- Make_BEATAML_deconvolution_annotated_heatmap(BEATAML_BPRNACAN3DProMet_deconvolution$deconvolution_df_IDH, BEATAML_BPRNACAN3DProMet_deconvolution$Pheno_deconvolution_IDH, "BEATAML_mIDH_samples_deconvolution_BPRNACAN3DProMet")
```

### Koichi data

```{r}
Clinical_KOICHI_data <- read.table("../Datasets/Clinical_Koichi_data.tsv", sep = "\t", header = T)

Prepare_KOICHI_deconvolution <- function(deconvolution_data_filename, sep){
  deconvolution_df <- read.table(paste0("../Results/Deconvolution/", deconvolution_data_filename), sep = sep, header = T)
  Pheno_Cluster <- sapply(deconvolution_df$Mixture, function(samples){
    dplyr::filter(Clinical_KOICHI_data, Baseline_RNAseq_data == samples) %>% .$Cluster
  })
  Pheno_Response <- sapply(deconvolution_df$Mixture, function(samples){
    dplyr::filter(Clinical_KOICHI_data, Baseline_RNAseq_data == samples) %>% .$Best_response
  })
  Pheno_IDH <- sapply(deconvolution_df$Mixture, function(samples){
    dplyr::filter(Clinical_KOICHI_data, Baseline_RNAseq_data == samples) %>% .$IDH_isoform
  })
  Pheno_deconvolution <- data.frame(id = deconvolution_df$Mixture,
                                    Cluster = Pheno_Cluster,
                                    Response = Pheno_Response,
                                    IDH = Pheno_IDH)
  list(Pheno_deconvolution = Pheno_deconvolution, deconvolution_df = deconvolution_df)
}
```

```{r}
KOICHI_JohnD_deconvolution <- Prepare_KOICHI_deconvolution(deconvolution_data_filename = "CIBERSORTx_JohnD_KOICHI_Results.tsv", "\t")
KOICHI_BPRNACAN3DProMet_deconvolution <- Prepare_KOICHI_deconvolution(deconvolution_data_filename = "CIBERSORTx_BPRNACAN3DProMet_Koichi_Results.tsv", "\t")

KOICHI_JohnD_deconvolution$deconvolution_df <- KOICHI_JohnD_deconvolution$deconvolution_df[,order_JohnD_signatures]
```

```{r}
Make_KOICHI_deconvolution_annotated_heatmap <- function(deconvolution_df, Pheno, title){
  annotation_for_heatmap <- Pheno
  rownames(annotation_for_heatmap) <- annotation_for_heatmap$id
  annotation_for_heatmap <- annotation_for_heatmap %>% dplyr::select(-"id")
  ann_color <- list(
    Cluster = c(Cluster_NR = "red",  Cluster_R= "blue", No_clustered = "grey"),
    Response = c(CR = "green", CRp = "darkgreen", HI = "blue", PR = "blue", MLFS = "blue", PD = "darkred", SD = "red"),
    IDH = c(IDH1 = "red", IDH2 = "green", IDH1_IDH2 = "violet")
    )
  ncolumn <- ncol(deconvolution_df)
  data4heatmap <- deconvolution_df[1:(ncolumn-3)]
  rownames(data4heatmap) <- data4heatmap$Mixture
  data4heatmap <- data4heatmap[-1]
  heatmap <- pheatmap(data4heatmap, 
                      color = rev(colorRampPalette(brewer.pal(n = 9, name = "RdBu"))(100)),
                      annotation_row = annotation_for_heatmap,
                      annotation_colors = ann_color,
                      legend = TRUE,
                      treeheight_row = 20,
                      main = title, 
                      fontsize = 10, scale = "row", show_rownames = F, cluster_cols = F
  )
  ggsave(paste0("../Results/Deconvolution/Heatmap_", title, ".png"), heatmap)
  return(heatmap)
}
```

```{r}
KOICHI_all_samples_JohnD_deconvolution_heatmap <- Make_KOICHI_deconvolution_annotated_heatmap(KOICHI_JohnD_deconvolution$deconvolution_df, KOICHI_JohnD_deconvolution$Pheno_deconvolution, "KOICHI_baseline_deconvolution_JohnD")
KOICHI_all_samples_BPRNACAN3DProMet_deconvolution_heatmap <- Make_KOICHI_deconvolution_annotated_heatmap(KOICHI_BPRNACAN3DProMet_deconvolution$deconvolution_df, KOICHI_JohnD_deconvolution$Pheno_deconvolution, "KOICHI_baseline_deconvolution_BPRNACAN3DProMet")

```

