---
title: "Koichi_Cluster_Chromatine_GRN_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
```

```{r}
suppressPackageStartupMessages({
  library(igraph)
  library(stringr)
  library(data.table)
  library(dplyr)
  library(matrixStats)
  library(ggplot2)
  library(clusterProfiler)
  library(DOSE)
  library(enrichplot)
})
```

```{r}
HSC_chromatine_network <- read.table("../Results/Network_analysis/HSC_Network_Cluster_Cytoscape_Chromatine.tsv", sep = "\t", header = T)
Chromatine_network <- read.table("../Results/Network_analysis/Network_Cluster_Cytoscape_Chromatine.tsv", sep = "\t", header = T)
GRN_network <- read.table("../Results/Network_analysis/Network_Cluster_Cytoscape_GRN.tsv", sep = "\t", header = T) %>% .[,c("source", "target")]
HSC_Chromatine_features <- read.table("../Results/Network_analysis/HSC_Nodes_Cluster_Cytoscape_Chromatine.tsv", sep = "\t", header = T)
Chromatine_features <- read.table("../Results/Network_analysis/Nodes_Cluster_Cytoscape_GRN.tsv", sep = "\t", header = T)
GRN_features <- read.table("../Results/Network_analysis/Nodes_Cluster_Cytoscape_GRN.tsv", sep = "\t", header = T)
```

```{r}
Genes_in_Chromatine <- c(Chromatine_network$source, Chromatine_network$target) %>% .[stringr::str_detect(., "[:alpha:]")] %>% unique
Genes_in_GRN <-  c(GRN_network$source, GRN_network$target) %>% unique

Genes_intersect_Chromatine_GRN <- intersect(Genes_in_Chromatine, Genes_in_GRN) %>% unique
```

```{r}
Genes_in_HSC_Chromatine <- c(HSC_chromatine_network$source, HSC_chromatine_network$target) %>% .[stringr::str_detect(., "[:alpha:]")] %>% unique
Genes_in_GRN <-  c(GRN_network$source, GRN_network$target) %>% unique

Genes_intersect_HSC_Chromatine_GRN <- intersect(Genes_in_HSC_Chromatine, Genes_in_GRN) %>% unique
```

```{r}
GO_overlap_GRN_chromatine <- enrichGO(gene = Genes_intersect_Chromatine_GRN, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_overlap_GRN_chromatine, showCategory=20)
png("../Results/Network_analysis/Chromatine_GRN_GO.png")
dotplot(GO_overlap_GRN_chromatine, showCategory=20)
dev.off()
```

```{r}
GO_overlap_GRN_HSC_chromatine <- enrichGO(gene = Genes_intersect_HSC_Chromatine_GRN, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_overlap_GRN_HSC_chromatine, showCategory=20)
png("../Results/Network_analysis/HSC_Chromatine_GRN_GO.png")
dotplot(GO_overlap_GRN_HSC_chromatine, showCategory=20)
dev.off()
```

```{r}
Genes_in_Chromatine_dCpGs <- Chromatine_features %>% dplyr::filter(P.Value < 0.05 & logFC > 0.3) %>% .$id %>% .[stringr::str_detect(., "[:alpha:]")] %>% unique
Genes_in_GRN_DEG_dTF <- GRN_features %>% dplyr::filter(pval < 0.1 | (abs(logFC) > 1.5 & P.Value < 0.05)) %>% .$id %>% unique

Genes_intersect_Chromatine_GRN_filtered <- intersect(Genes_in_Chromatine_dCpGs, Genes_in_GRN_DEG_dTF) %>% unique
```

```{r}
Genes_in_HSC_Chromatine_dCpGs <- HSC_Chromatine_features %>% dplyr::filter(P.Value < 0.05 & logFC > 0.3) %>% .$id %>% .[stringr::str_detect(., "[:alpha:]")] %>% unique
Genes_in_GRN_DEG_dTF <- GRN_features %>% dplyr::filter(pval < 0.1 | (abs(logFC) > 1.5 & P.Value < 0.05)) %>% .$id %>% unique

Genes_intersect_HSC_Chromatine_GRN_filtered <- intersect(Genes_in_HSC_Chromatine_dCpGs, Genes_in_GRN_DEG_dTF) %>% unique
```

```{r}
GO_intersect_filtered_chromatine_GRN <- enrichGO(gene = Genes_intersect_Chromatine_GRN_filtered, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_intersect_filtered_chromatine_GRN, showCategory=20)
png("../Results/Network_analysis/Chromatine_GRN_filtered_GO.png")
dotplot(GO_intersect_filtered_chromatine_GRN, showCategory=20)
dev.off()
```

```{r}
GO_intersect_filtered_HSC_chromatine_GRN <- enrichGO(gene = Genes_intersect_HSC_Chromatine_GRN_filtered, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_intersect_filtered_HSC_chromatine_GRN, showCategory=20)
png("../Results/Network_analysis/HSC_Chromatine_GRN_filtered_GO.png")
dotplot(GO_intersect_filtered_HSC_chromatine_GRN, showCategory=20)
dev.off()
```

```{r}
GO_intersect_filtered_chromatine <- enrichGO(gene = Genes_in_Chromatine_dCpGs, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
png("../Results/Network_analysis/Chromatine_filtered_GO.png")
dotplot(GO_intersect_filtered_chromatine, showCategory=20)
dev.off()
GO_chromatine <- enrichGO(gene = Genes_in_Chromatine, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
png("../Results/Network_analysis/Chromatine_GO.png")
dotplot(GO_chromatine, showCategory=20)
dev.off()
dotplot(GO_intersect_filtered_chromatine, showCategory=20)
dotplot(GO_chromatine, showCategory=20)
```

```{r}
GO_intersect_filtered_HSC_chromatine <- enrichGO(gene = Genes_in_HSC_Chromatine_dCpGs, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
png("../Results/Network_analysis/HSC_Chromatine_filtered_GO.png")
dotplot(GO_intersect_filtered_HSC_chromatine, showCategory=20)
dev.off()
GO_HSC_chromatine <- enrichGO(gene = Genes_in_HSC_Chromatine, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
png("../Results/Network_analysis/HSC_Chromatine_GO.png")
dotplot(GO_HSC_chromatine, showCategory=20)
dev.off()
dotplot(GO_intersect_filtered_HSC_chromatine, showCategory=20)
dotplot(GO_HSC_chromatine, showCategory=20)
```