---
title: "Koichi_DNA_methylation_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
```


```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(chaser)
  library(stringr)
  library(gridExtra)
  library(grid)
  library(ggplot2)
  library(GenomicRanges)
  library(ChAMP)
  library(limma)
  library(factoextra)
  library(Hmisc)
  library(pheatmap)
  library(RColorBrewer)
  library(EnhancedVolcano)
})

source("~/Core_scripts/core_functions.R")
source("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Make_koichi_factor.R")
```

```{r}
Differential_analysis <- function(Focused_variable, DATA){
  design.pairs <- function(levels) {
    n <- length(levels)
    design <- matrix(0,n,choose(n,2))
    rownames(design) <- levels
    colnames(design) <- 1:choose(n,2)
    k <- 0
    for (i in 1:(n - 1))
      for (j in (i + 1):n) {
        k <- k + 1
        design[i,k] <- 1
        design[j,k] <- -1
        colnames(design)[k] <- paste(levels[i], "-", levels[j],sep = "")
      }
    design
  }
  design <- model.matrix(~0 + Focused_variable)
  contr.matrix <- design.pairs(levels(factor(Focused_variable)))
  colnames(design) <- rownames(contr.matrix)   
  Fit <- lmFit(DATA, design) %>%
    contrasts.fit(., contr.matrix) %>%
    eBayes(., trend = TRUE)
  
  FitList <- list()
  for (i in 1:ncol(contr.matrix)) {
    FitList[[i]] <- topTable(Fit, coef = i, adjust.method = "BH", number = nrow(DATA)) %>%
      mutate(ID = rownames(.))
    
    message(paste0(i, " done"))
    
  }
  names(FitList) <- colnames(contr.matrix)
  return(FitList)
}


Make_factor_DNA_meth <- function(samples, Phenotype){
  res <- sapply(samples, function(s){
    if(s %in% Phenotype$Baseline_Sample){
      p <- "B"
      resp <- Phenotype[which(Phenotype$Baseline_Sample == s), "Best_response"][1]
      if(resp %in% c("CR", "CRi")){
        p <- paste(p, "R", sep = "_")
      }else if(resp %in% c("SD", "PD")){
        p <- paste(p, "NR", sep = "_")
      }else{
        p <- paste(p, "OR", sep = "_")
      }
    }else{
      p <- "PostT"
      resp <- Phenotype[which(Phenotype$Post_treatment_sample == s), "Best_response"][1]
      if(resp %in% c("CR", "CRi")){
        p <- paste(p, "R", sep = "_")
      }else if(resp %in% c("SD", "PD")){
        p <- paste(p, "NR", sep = "_")
      }else{
        p <- paste(p, "OR", sep = "_")
      }
    }
    p
  })
  res <- unname(res)
  return(res)
}
```

```{r}
BMIQ <- readRDS("/media/alexis/DATA/Koichi_methylation_dat/BMIQ_norm_Koichi_samples.Rdata")
NR_R_Factor <- Make_factor_DNA_meth(colnames(BMIQ), Clinical_patient_data)
BMIQ <- BMIQ %>% as.data.frame() %>% .[,NR_R_Factor == "B_R" | NR_R_Factor == "B_NR" | NR_R_Factor == "B_OR"]
NR_R_Factor <- Make_factor_DNA_meth(colnames(BMIQ), Clinical_patient_data)
```


```{r}
res.pca <- prcomp(t(BMIQ))
p <- fviz_pca_ind(res.pca, label="all", habillage=NR_R_Factor, addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA DNA methylation")
p
png("../Results/DNAmethylation/PCA_DNA_methylation.png")
p
dev.off()
```

```{r}
Make_heatmap <- function(DATA, Phenotype, mutation_pheno, method = "pearson", 
                         title, annotation_color, kmeans_k = NA, cuttree = NA, corr=T) {
  annotation_for_heatmap <- data.frame(Phenotype = Phenotype$Phenotype, IDH_isoform = mutation_pheno)
  rownames(annotation_for_heatmap) <- colnames(DATA)
  if(corr){
    corr <- rcorr(as.matrix(DATA), type = method)$r
    colnames(corr) <- colnames(DATA)
  }else{
    corr <- DATA
  }
  title <- paste0(title, " ", method)
  heatmap <- pheatmap(corr, 
                      color = colorRampPalette(brewer.pal(n = 9, name = "YlOrRd"))(100),
                      annotation_col = annotation_for_heatmap,
                      annotation_colors = annotation_color,
                      legend = TRUE,
                      treeheight_row = 20,
                      main = title, 
                      fontsize = 10,
                      cutree_cols = cuttree
  )
  return(heatmap)
}
```



```{r}
Pheno_IDHm <- sapply(colnames(BMIQ), function(sample){
  dplyr::filter(Clinical_patient_data, Baseline_Sample == sample) %>% .$IDH_isoform
})
Var_cpgs <- rowVars(as.matrix(BMIQ))
names(Var_cpgs) <- rownames(BMIQ)
pourcent_cpgs <- 0.5
method = "spearman"
nb_cpg <- pourcent_cpgs*nrow(BMIQ)%/%100 
Top_var_cpgs <- Var_cpgs[order(Var_cpgs, decreasing = T)] %>% .[1:nb_cpg]
Top_Var_BMIQ <- BMIQ %>% .[rownames(.) %in% names(Top_var_cpgs),]

ann_color_BMIQ <- list(
    Phenotype = c(B_R = "blue", B_NR = "red", B_OR = "green"),
    IDH_isoform = c(IDH1 = "blue", IDH2 = "red", IDH1_IDH2 = "red"))

pheno_heatmap <- data.frame("Responder" = NR_R_Factor == "B_R", "Non_responder" = NR_R_Factor == "B_NR")
pheno_heatmap$Phenotype <- NR_R_Factor
heat <- Make_heatmap(Top_Var_BMIQ, Phenotype = pheno_heatmap,mutation_pheno = Pheno_IDHm, title = paste0("Patient correlation of Top ", pourcent_cpgs, "% variable cpg"), annotation_color = ann_color_BMIQ, method = method)

png(paste0("../Results/DNAmethylation/Heatmap_DNAmeth_top_", pourcent_cpgs,"_", method, "_method_Koichi_data.png"))
heat
dev.off()

res.pca <- prcomp(t(Top_Var_BMIQ))
p <- fviz_pca_ind(res.pca, label="all", habillage=NR_R_Factor,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA DNA methylation")
p
png(paste0("../Results/DNAmethylation/PCA_Top_", pourcent_cpgs, "_cpgs_DNA_methylation.png"))
p
dev.off()
if(pourcent_cpgs < 1){
  heat2 <- Make_heatmap(Top_Var_BMIQ, Phenotype = pheno_heatmap, mutation_pheno = Pheno_IDHm, title = paste0("Patient correlation of Top ", pourcent_cpgs, "% variable cpg"), annotation_color = ann_color_BMIQ, method = method, corr = F)
}
```

```{r}
fisher.test(data.frame(CLuster1=c(14,16), Cluster2=c(12,41)))
```


```{r}
pourcent_cpgs <- 0.5
nb_cpg <- pourcent_cpgs*nrow(BMIQ)%/%100 
Top_var_cpgs <- Var_cpgs[order(Var_cpgs, decreasing = T)] %>% .[1:nb_cpg]
Top_Var_BMIQ <- BMIQ %>% .[rownames(.) %in% names(Top_var_cpgs),]

p <- fviz_nbclust(Top_Var_BMIQ, kmeans, method = "silhouette") +
  labs(subtitle = "Silhouette method")
p
png(paste0("../Results/DNAmethylation/Number_Cluster_Top_", pourcent_cpgs, "_cpgs_DNA_methylation.png"))
p
dev.off() 
```

```{r}
R_samples <- colnames(Top_Var_BMIQ[heat$tree_col[["order"]]])[1:41]
NR_samples <-  colnames(Top_Var_BMIQ[heat$tree_col[["order"]]])[42:57]
```

```{r}
Pheno_cluster <- colnames(BMIQ) %in% R_samples
Pheno_cluster <- ifelse(Pheno_cluster, "Cluster_R", "Cluster_NR")
Cluster_DMP <- Differential_analysis(Pheno_cluster, BMIQ)$`Cluster_NR-Cluster_R`

write.table(Cluster_DMP, "../Results/DNAmethylation/DMP_CLusterNR_R.tsv", sep = "\t", row.names = F, quote = F)

Volcano <- EnhancedVolcano(Cluster_DMP, 
                           lab = rownames(Cluster_DMP), 
                           x = 'logFC', y = 'P.Value', 
                           FCcutoff = 0.15, 
                           title="Cluster DMP", 
                           shape = 1, xlim = c(-0.6,0.6))

png(paste0("../Results/DNAmethylation/Clusters_DMP_volcanoplot.png"))
Volcano
dev.off()
```

```{r}
res.pca <- prcomp(t(Top_Var_BMIQ))
p <- fviz_pca_ind(res.pca, label="all", habillage=Pheno_cluster,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA DNA methylation and Cluster")
p
png("../Results/DNAmethylation/PCA_top_0.5_cpgs_Clusters_DNA_methylation.png")
p
dev.off()
```

```{r}
NR_Patient_ID <- Clinical_patient_data %>% 
  dplyr::filter(Baseline_Sample %in% NR_samples) %>% 
  .$patient_id

R_Patient_ID <- Clinical_patient_data %>% 
  dplyr::filter(Baseline_Sample %in% R_samples) %>% 
  .$patient_id

Clinical_patient_data$Cluster <- sapply(Clinical_patient_data$patient_id, function(id){
  if(id %in% NR_Patient_ID){
    "Cluster_NR"
  }else if(id %in% R_Patient_ID){
    "Cluster_R"
  }else{
    "No_clustered"
  }
})

write.table(Clinical_patient_data, "../Datasets/Clinical_Koichi_data.tsv", sep = "\t", row.names = F)
```
