---
title: "Koichi_Cluster_Metabolic_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())

suppressPackageStartupMessages({
  library(dplyr)
  library(matrixTests)
  library(factoextra)
  library(Hmisc)
  library(matrixStats)
  library(RColorBrewer)
  library(pheatmap)
  library(data.table)
})

source("~/Core_scripts/core_functions.R")
source("~/GitHub/Multiplex_DNAmet_PPI_Chrom_Coexp/Make_koichi_factor.R")
```


```{r}
mIDHi_react_scores_GEM <- read.csv("../Datasets/mIDHi_react_scores_GEM.csv", check.names = F, row.names = 1)
colnames(mIDHi_react_scores_GEM) <- colnames(mIDHi_react_scores_GEM) %>% 
  stringr::str_remove("X")
Clinical_patient_data <- read.table("../Datasets/Clinical_Koichi_data.tsv", sep = "\t", header = T)
```


```{r}
Cluster_pheno <- colnames(mIDHi_react_scores_GEM) %>% sapply(function(sample){
  if(sample %in% Clinical_patient_data$Relapse_RNAseq_data){
    "Relapse"
  }else{
    Clinical_patient_data %>% dplyr::filter(Baseline_RNAseq_data == sample) %>% .$Cluster
  }
})
mIDHi_react_scores_GEM <- mIDHi_react_scores_GEM[,Cluster_pheno == "Cluster_NR" | Cluster_pheno == "Cluster_R"]
Cluster_pheno <- Cluster_pheno[Cluster_pheno == "Cluster_NR" | Cluster_pheno == "Cluster_R"]
```

```{r}
res.pca <- prcomp(t(mIDHi_react_scores_GEM))
p <- fviz_pca_ind(res.pca, label="all", habillage=Cluster_pheno,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA reactions activities")
p
png("../Results/Metabolism/PCA_Koichi_metabolic_reaction_data_Clusters.png")
p
dev.off()
```

```{r}
Make_heatmap <- function(DATA, Phenotype, method = "pearson", title, annotation_color, kmeans_k = NA, cuttree = NA, corr=T, TF=F) {
  annotation_for_heatmap <- data.frame(Phenotype = Phenotype$Phenotype)
  rownames(annotation_for_heatmap) <- colnames(DATA)
  if(corr){
    corr <- rcorr(as.matrix(DATA), type = method)$r
    colnames(corr) <- colnames(DATA)
    if(TF){
      color= rev(colorRampPalette(brewer.pal(n = 9, name = "RdBu"))(100))
    }else{
      color = colorRampPalette(brewer.pal(n = 9, name = "YlOrRd"))(100)
    }
  }else{
    corr=DATA
    color= rev(colorRampPalette(brewer.pal(n = 9, name = "RdBu"))(100))
  }
  
  title <- paste0(title, " ", method)
  heatmap <- pheatmap(corr, 
                      color = color,
                      annotation_col = annotation_for_heatmap,
                      annotation_colors = annotation_color,
                      legend = TRUE,
                      treeheight_row = 20,
                      main = title, 
                      fontsize = 10,
                      cutree_cols = cuttree
  )
  return(heatmap)
}
```

```{r}
Var_reactions <- rowVars(as.matrix(mIDHi_react_scores_GEM))
names(Var_reactions) <- rownames(mIDHi_react_scores_GEM)
```

```{r}
nb_reactions <- 15303
method <- "spearman"
```

```{r}
Top_var_reactions <- Var_reactions[order(Var_reactions, decreasing = T)] %>% .[1:nb_reactions]
Top_Var_mIDHi_react_scores <- mIDHi_react_scores_GEM %>% .[rownames(.) %in% names(Top_var_reactions),] 
ann_color_RNA <- list(
    Phenotype = c(Cluster_R = "blue", Cluster_NR = "red"))

pheno_heatmap <- data.frame("Responder" = Cluster_pheno == "Cluster_R", "Non_responder" = Cluster_pheno == "Cluster_NR")
pheno_heatmap$Phenotype <- Cluster_pheno
heat <- Make_heatmap(Top_Var_mIDHi_react_scores, Phenotype = pheno_heatmap, title = paste0("Patient correlation of Top ", nb_reactions, " variable reactions activities"), annotation_color = ann_color_RNA, method = method)

png(paste0("../Results/Metabolism/Heatmap_Clusters_GE_top_", nb_reactions,"_reactions_corr_", method, "_Koichi_data.png"))
heat
dev.off()

res.pca <- prcomp(t(Top_Var_mIDHi_react_scores))
p <- fviz_pca_ind(res.pca, label="all", habillage=Cluster_pheno,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle(paste0("PCA top ", nb_reactions, " reactions"))
p
png(paste0("../Results/DGEA/PCA_Clusters_GE_top_", nb_reactions,"_reactions_Koichi_data.png"))
p
dev.off()
if(nb_reactions < 500){
  heat2 <- Make_heatmap(Top_Var_mIDHi_react_scores, Phenotype = pheno_heatmap, title = paste0("Patient Clusters correlation of Top ", nb_reactions, " variable reactions activity"), annotation_color = ann_color_RNA, method = "", corr = F)
  png(paste0("../Results/DGEA/Heatmap_Clusters_GE_top_", nb_reactions,"_reactions_Koichi_data.png"))
  heat2
  dev.off()
}
```


```{r}
t_test_pheno_comp <- function(pheno_df, phenoA, phenoB, df){
  res <- row_t_welch(df[, pheno_df == phenoA], df[, pheno_df == phenoB]) %>%
    dplyr::filter(pvalue < 0.05) %>%
    t()
  colnames(res) <- stringr::str_remove(colnames(res), pattern = "_pos")
  colnames(res) <- stringr::str_remove(colnames(res), pattern = "_neg")
  
  res[,!duplicated(colnames(res))] %>% t() %>% data.frame()
}
```

```{r}
Cluster_analysis <- t_test_pheno_comp(Cluster_pheno, "Cluster_NR", "Cluster_R", mIDHi_react_scores_GEM)

write.table(Cluster_analysis, "../Results/Metabolism/Cluster_T_test.tsv", sep = "\t", row.names = F)
```


```{r}
library(biomaRt)
Human_GEM <- read.csv("../Datasets/Human_GEM_2.csv")
```

```{r}
Metabo_reactions <- stringr::str_split(Human_GEM$EQUATION, pattern = "\\+ | => | <=>")

names(Metabo_reactions) <- Human_GEM$ID

Metabolic_network <- lapply(names(Metabo_reactions), function(reaction){
  purrr::reduce(.f = function(a, b) rbind(a, data.frame(A = reaction, B = b)), .x = Metabo_reactions[[reaction]], .init = data.frame(A  = reaction, B = Metabo_reactions[[reaction]][1]))[-1,]
}) %>% rbindlist()

Metabolic_network_clean <- dplyr::filter(Metabolic_network, B != "")

Metabolic_network_clean$B <- stringr::str_trim(Metabolic_network_clean$B)

Remove_coeff <- function(metab){
  if(length(metab) > 1){
    ifelse(stringr::str_detect(metab[1], pattern = "[:alpha:]"), Reduce(x=metab, f = paste), Reduce(x=metab[-1], f = paste))
  }else{
    metab
  }
}

Metabolic_network_clean$B <- sapply(Metabolic_network_clean$B, function(metabolite){
  stringr::str_split(metabolite, pattern = "[:space:]") %>% .[[1]] %>% Remove_coeff()
})

Metabolic_network_clean <- unique(Metabolic_network_clean)

write.table(Metabolic_network_clean, "../Results/Metabolism/Metabolic_network_clean.tsv", sep = "\t", row.names = F, quote = F)
```


```{r}
Gene_to_convert <- Human_GEM$GENE.ASSOCIATION %>% stringr::str_split(pattern = " or ") %>% unlist() %>% unique()

ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")
genes_annotated <- getBM(attributes = c('hgnc_symbol', 'ensembl_gene_id'), filters = 'ensembl_gene_id', values = Gene_to_convert, mart = ensembl)
```

```{r}
Reaction_Gene_asso <- Human_GEM[,c(1,4)]

Gene_reactions <- stringr::str_split(Reaction_Gene_asso$GENE.ASSOCIATION, pattern = " or ")

names(Gene_reactions) <- Human_GEM$ID

Gene_converter <- genes_annotated$hgnc_symbol
names(Gene_converter) <- genes_annotated$ensembl_gene_id

Gene_reactions <- lapply(Gene_reactions, function(reaction){
  sapply(reaction, function(gene){
    Gene_converter[gene]
  }) %>% unique()
})
```


```{r}
Gene_reactions_network <- lapply(names(Gene_reactions), function(reaction){
  purrr::reduce(.f = function(a, b) rbind(a, data.frame(A = reaction, B = b)), .x = Gene_reactions[[reaction]], .init = data.frame(A  = reaction, B = Gene_reactions[[reaction]][1]))[-1,]
}) %>% data.table::rbindlist

Gene_reactions_network_cleaned <- na.omit(Gene_reactions_network)
Gene_reactions_network_cleaned <- dplyr::filter(Gene_reactions_network_cleaned, B != "")

Gene_reactions_network_cleaned_filtered <- Gene_reactions_network_cleaned[Gene_reactions_network_cleaned$A %in% rownames(Cluster_analysis),]

write.table(Gene_reactions_network_cleaned, "../Results/Metabolism/Gene_reactions_network.tsv", sep = "\t", row.names = F, quote = F)
write.table(Gene_reactions_network_cleaned_filtered, "../Results/Metabolism/Cluster_Gene_reactions_network_filtered.tsv", sep = "\t", row.names = F, quote = F)
Cluster_analysis$name <- rownames(Cluster_analysis)
Cluster_analysis[,c("name", "pvalue", "mean.diff")] %>% write.table("../Results/Metabolism/Cluster_Metabolic_features_filtered.tsv", sep = "\t", quote = F, row.names = F)

Metabolic_network_clean_Cluster <- dplyr::filter(Metabolic_network_clean, A %in% Cluster_analysis$name)
Metabolic_network_clean_Cluster_filtered <- Metabolic_network_clean_Cluster 
Metabolic_network_clean_Cluster_filtered$B <- stringr::str_replace_all(Metabolic_network_clean_Cluster_filtered$B, pattern = " ", replacement = ",")
write.table(Metabolic_network_clean_Cluster_filtered, "../Results/Metabolism/Metabolic_network_clean_filtered_Clusters.tsv", sep = "\t", row.names = F, quote = F)
```

