---
title: "Koichi_Cluster_GRN_Metabolic_analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r}
rm(list = ls())
```

```{r}
suppressPackageStartupMessages({
  library(igraph)
  library(stringr)
  library(data.table)
  library(dplyr)
  library(matrixStats)
  library(ggplot2)
  library(clusterProfiler)
})

"%ni%" <- Negate("%in%")
```

```{r}
GRN_network <- read.table("../Results/Network_analysis/Network_Cluster_Cytoscape_GRN.tsv", sep = "\t", header = T) %>% .[,c("source", "target")]
GRN_features <- read.table("../Results/Network_analysis/Nodes_Cluster_Cytoscape_GRN.tsv", sep = "\t", header = T)
PPI_base <- read.csv("~/Documents/List_genes_from_transcriptome/FIsInGene_020720_with_annotations.tsv", sep = "\t")
Annotations_PPI <- PPI_base %>% tidyr::separate_rows(., Annotation, sep = ";") %>% .$Annotation %>% unique %>% stringr::str_remove_all(" ") %>% unique
Annotations_PPI %>% write.table("../Results/fPPI/Annotations.tsv", sep = "\t", row.names = F, col.names = F)
Metabo_network <- read.table("../Results/Metabolism/Metabolic_network_clean_filtered_Clusters.tsv", sep = "\t", header = T)$A %>% unique()
Metabo_converter <- read.table("../Results/Metabolism/Gene_reactions_network.tsv", sep = "\t", header = T)
```

```{r}
Annotations_PPI_cleaned <- Annotations_PPI <- PPI_base %>% tidyr::separate_rows(., Annotation, sep = ";")
Annotations_PPI_cleaned$Annotation <- stringr::str_remove_all(Annotations_PPI_cleaned$Annotation, " ")
Annotation_PPI_2_remove <- read.table("../Results/fPPI/Annotations_2_remove.csv", sep = "\t", header = F)$V1
Annotations_PPI_cleaned <- dplyr::filter(Annotations_PPI_cleaned, Annotation %ni% Annotation_PPI_2_remove & Score > 0.7)
Annotations_PPI_cleaned <- Annotations_PPI_cleaned[,c("Gene1", "Gene2", "Direction", "Score")] %>% unique()
Annotations_PPI_cleaned %>% write.table("../Results/fPPI/Annotations_cleaned.tsv", row.names = F, sep = "\t")
```


```{r}
Genes_in_GRN <-  c(GRN_network$source, GRN_network$target) %>% unique
Genes_DEG <- GRN_features %>% dplyr::filter((P.Value < 0.05 & logFC > 1.5) | pval < 0.1) %>% .$id %>% unique
Genes_in_fPPI <- c(Annotations_PPI_cleaned$Gene1, Annotations_PPI_cleaned$Gene2) %>% unique
intersect(Genes_in_GRN, Genes_in_fPPI) %>% length
```

```{r}
Genes_in_Metabo <- Metabo_network %>% sapply(function(reaction){
  Metabo_converter[Metabo_converter$A == reaction, "B"]
}) %>% unlist() %>% unique()
Genes_intersect_Metabo_GRN <- intersect(Genes_in_GRN, Genes_in_Metabo)
Genes_intersect_Metabo_DEG <- intersect(Genes_DEG, Genes_in_Metabo)
```

```{r}
GO_overlap_Metabo_GRN <- enrichGO(gene = Genes_intersect_Metabo_GRN, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_overlap_Metabo_GRN, showCategory=20)
png("../Results/Network_analysis/Metabo_GRN_GO.png")
dotplot(GO_overlap_Metabo_GRN, showCategory=20)
dev.off()
```

```{r}
GO_Metabo <- enrichGO(gene = Genes_in_Metabo, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", pvalueCutoff = 0.05, pAdjustMethod = "none", qvalueCutoff = 1)
dotplot(GO_Metabo, showCategory=20)
png("../Results/Network_analysis/Metabo_GO.png")
dotplot(GO_Metabo, showCategory=20)
dev.off()
```


