---
title: "Layers_Making"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r, warning=F, include=F, echo=F, message=F}
library(dplyr)

load("/media/alexis/DATA/Session/R_session/Cluster_GRN_network_analysis.RData")

rm(DOLite, DOLiteTerm, RnIALite, HsIALite, DmIALite, MmIALite)
```

```{r}
logFC_threshold <- 1.5
pvalue_threshold <- 0.05
pvalue_TF_threshold <- 0.1

genes_of_interest <- Cluster_DEG %>%
  dplyr::filter(abs(logFC) > logFC_threshold & P.Value < pvalue_threshold) %>% 
  .$ID

TF_of_interest <- Cluster_TF_activity_msviper %>%
  dplyr::filter(pval < pvalue_TF_threshold) %>%
  .$TF

nodes_of_interest <- c(genes_of_interest, TF_of_interest) %>%
  unique

Filtered_GRN_network <- Cluster_TF_activity_msviper_network %>%
  dplyr::filter(tf %in% nodes_of_interest | target %in% nodes_of_interest)

write.table(Filtered_GRN_network, "../Results/Network_4_Multilayer/Filtered_GRN_network.tsv", sep ="\t")
```

```{r}
load("/media/alexis/DATA/Session/R_session/Thesis_paper_Rsessions/Chromatine_network_making.RData")
```

