---
title: "TCGA IDHms data analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r, error=FALSE}
rm(list = ls())

suppressPackageStartupMessages({
  library(FactoMineR)
  library(igraph)
  library(limma)
  library(viper)
  library(stringr)
  library(data.table)
  library(dplyr)
  library(RCy3)
  library(factoextra)
  library(pheatmap)
  library(Hmisc)
  library(matrixStats)
  library(RColorBrewer)
})

"%ni%" <- Negate("%in%")
wd <- "~/GitHub/Thesis_paper/"
source("~/Core_scripts/msviper_functions.R")
source("~/Core_scripts/core_functions.R")
```

```{r}
RNAseqTCGA <- read.table("../Datasets/RNAseqTCGA.tsv", sep = "\t", header = T)
Pheno_TCGA <- sapply(colnames(RNAseqTCGA), function(samples){
  IDH1 <- stringr::str_detect(samples, pattern = "mIDH1")
  IDH2 <- stringr::str_detect(samples, pattern = "mIDH2")
  ifelse(IDH1, "mIDH1", ifelse(IDH2, "mIDH2", "wtIDH"))
})
```

```{r}
Voom_TCGA <- voom(RNAseqTCGA[Pheno_TCGA != "wtIDH"])$E
Pheno_TCGA_IDH <- Pheno_TCGA[Pheno_TCGA != "wtIDH"]
```

```{r}
res.pca <- prcomp(t(Voom_TCGA))
p <- fviz_pca_ind(res.pca, label="all", habillage=Pheno_TCGA_IDH,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA gene expression")
p
png("../Results/DGEA/PCA_TCGA_IDH_data.png")
p
dev.off()
```

```{r}
TCGA_ARACNe_network <- read.table("../Results/DGEA/Networks/network.txt", sep = "\t", header = T)
colnames(TCGA_ARACNe_network)[1:2] <- c("tf", "target")

ref_mIDH1 <- Pheno_TCGA_IDH == "mIDH1"
ref_mIDH2 <- Pheno_TCGA_IDH == "mIDH2"

IDH_TCGA_msvip <- run_msviper(Voom_TCGA, TCGA_ARACNe_network, use_aracne = T, ref_mIDH1, ref_mIDH2, "mIDH1", "mIDH2", minsize = 4, ges.filter = T)
IDH_TCGA_TF_actitity <- viper(Voom_TCGA, dorothea2viper_regulons(IDH_TCGA_msvip$regulons))
IDH_TCGA_msvip$mrs_table %>% dplyr::filter(pval < 0.05) %>% write.table("../Results/DGEA/Filtered_TF_Diff_activity_TCGA_IDH.tsv", sep = "\t")
```

```{r}
plot(IDH_TCGA_msvip$mrs, mrs = 50)
png("../Results/DGEA_Clusters_Clean/Cluster_TCGA_IDH_msviplot.png", width = 1280, height = 720)
plot(IDH_TCGA_msvip$mrs, mrs = 50)
dev.off()

```

```{r}
DEG_IDH_TCGA <- Differential_analysis(Pheno_TCGA_IDH, Voom_TCGA)$`mIDH1-mIDH2`

```

