---
title: "Verhaak data analysis"
author: Alexis Hucteau
date: "`r Sys.Date()`"
output:
    html_document:
      toc: yes
      toc_float: yes
      theme: united
editor_options:
  markdown:
    wrap: sentence
---

```{r, error=FALSE}
library(FactoMineR)
library(igraph)
library(limma)
library(viper)
library(stringr)
library(data.table)
library(dplyr)
library(RCy3)
library(factoextra)
library(pheatmap)
library(Hmisc)
library(matrixStats)
library(RColorBrewer)
library(EnhancedVolcano)
library(grid)
library(gridExtra)


"%ni%" <- Negate("%in%")
wd <- "~/GitHub/Thesis_paper/"
source("~/Core_scripts/core_functions.R")
source("~/Core_scripts/msviper_functions.R")
```


```{r}
Verhaak_affy <- read.table("/media/alexis/DATA/Thesis_paper_DATA/MatriceIDHVerhaak.gct", sep = "\t", skip = 2, header = T)
Verhaak_Clinical <- read.table("../Datasets/Clinical_Verhaak.tsv", sep = "\t", header = T) %>% t
colnames(Verhaak_Clinical) <- Verhaak_Clinical[1,]
Verhaak_Clinical <- Verhaak_Clinical[-1,]
Verhaak_Clinical %>%
  write.table("../Datasets/Verhaak_Clinical_prepared.tsv", sep = "\t", col.names = NA)
```

```{r}
Verhaak_final <- Verhaak_affy %>%
  split(., .$Gene.Symbol) %>% 
    lapply(., function(x){
      l <- ncol(x)
      cnames <- colnames(x)[3:l]
      df <- x[,3:l] %>%
        as.matrix %>%
        colMaxs %>% 
        data.frame %>%
        t %>%
        data.frame
      colnames(df) <- cnames
      df
    })
Gene_Symbol <- Verhaak_affy %>%
  split(., .$Gene.Symbol) %>%
  names()
Gene_Symbol <- Gene_Symbol[-1]
Verhaak_final_2 <- data.table::rbindlist(Verhaak_final)
Verhaak_final_2 <- Verhaak_final_2[-1,]
rownames(Verhaak_final_2) <- Gene_Symbol

Verhaak_final_2 %>% 
  write.table("../Datasets/Verhaak_formated.tsv", sep = "\t", col.names = NA)
```

```{r}
Verhaak_final_2 <- read.table("/media/alexis/DATA/Thesis_paper_DATA/Verhaak_formated.tsv", sep = "\t", header = T, row.names = 1)
Verhaak_final <- na.omit(Verhaak_final_2)
Verhaak_Clinical <- read.table("../Datasets/Verhaak_Clinical_prepared.tsv", sep = "\t", header = T, row.names = 1)
Pheno_affy_IDH <- sapply(colnames(Verhaak_final_2), function(samples){
  patient <- dplyr::filter(Verhaak_Clinical, ID == samples)
  IDH1 <- ifelse(patient$IDH1 == 1, "mIDH1", "wtIDH1")
  IDH2 <- ifelse(patient$IDH2 == 1, "mIDH2", "wtIDH2")
  paste(IDH1, IDH2, sep = "_")
})
Patient_OS_summary <- summary(Verhaak_Clinical$OS)
Pheno_affy_OS <- sapply(colnames(Verhaak_final_2), function(samples){
  patient_OS <- dplyr::filter(Verhaak_Clinical, ID == samples) %>% .$OS
  ifelse(patient_OS < Patient_OS_summary[2], "Low_OS", ifelse(patient_OS > Patient_OS_summary[5], "High_OS", "Overall_OS"))
})

res.pca <- prcomp(t(Verhaak_final))
p <- fviz_pca_ind(res.pca, label="all", habillage=Pheno_affy_OS,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA gene expression")
p
ggsave("../Results/DGEA/PCA_Verhaak_IDH_data.png", p)
```

```{r}
Verhaak_final_norm <- limma::voom(Verhaak_final)$E
res.pca <- prcomp(t(Verhaak_final_norm))
p <- fviz_pca_ind(res.pca, label="all", habillage=Pheno_affy_OS,
                               addEllipses=T, ellipse.level=0.95)
p <- p + ggtitle("PCA gene expression")
p
```


```{r}
DEG_analysis_IDH <- Differential_analysis(Pheno_affy_IDH, Verhaak_final)
DEG_analysis_OS <- Differential_analysis(Pheno_affy_OS, Verhaak_final)
mIDH1_vs_wtIDH_Verhaak <- DEG_analysis_IDH$`mIDH1_wtIDH2-wtIDH1_wtIDH2`
mIDH2_vs_wtIDH_Verhaak <- DEG_analysis_IDH$`wtIDH1_mIDH2-wtIDH1_wtIDH2`
mIDH1_vs_mIDH2_Verhaak <- DEG_analysis_IDH$`mIDH1_wtIDH2-wtIDH1_mIDH2`
High_OS_vs_Low_OS_Verhaak <- DEG_analysis_OS$`High_OS-Low_OS`

mIDH1_vs_wtIDH_Verhaak %>% write.table("../Results/DGEA/DEGs_tables/mIDH1_vs_wtIDH_Verhaak.tsv", sep = "\t", col.names = NA)
mIDH2_vs_wtIDH_Verhaak %>% write.table("../Results/DGEA/DEGs_tables/mIDH2_vs_wtIDH_Verhaak.tsv", sep = "\t", col.names = NA)
mIDH1_vs_mIDH2_Verhaak %>% write.table("../Results/DGEA/DEGs_tables/mIDH1_vs_mIDH2_Verhaak.tsv", sep = "\t", col.names = NA)
High_OS_vs_Low_OS_Verhaak %>% write.table("../Results/DGEA/DEGs_tables/High_OS_vs_Low_OS_Verhaak.tsv", sep = "\t", col.names = NA)

mIDH1_vs_wtIDH_Verhaak %>% dplyr::filter(abs(logFC) > 0.75 & P.Value < 0.05) %>% write.table("../Results/DGEA/Filtered_DEGs_tables/mIDH1_vs_wtIDH_Verhaak.tsv", sep = "\t", col.names = NA)
mIDH2_vs_wtIDH_Verhaak %>% dplyr::filter(abs(logFC) > 0.75 & P.Value < 0.05) %>% write.table("../Results/DGEA/Filtered_DEGs_tables/mIDH2_vs_wtIDH_Verhaak.tsv", sep = "\t", col.names = NA)
mIDH1_vs_mIDH2_Verhaak %>% dplyr::filter(abs(logFC) > 0.75 & P.Value < 0.05) %>% write.table("../Results/DGEA/Filtered_DEGs_tables/mIDH1_vs_mIDH2_Verhaak.tsv", sep = "\t", col.names = NA)
High_OS_vs_Low_OS_Verhaak %>% dplyr::filter(abs(logFC) > 0.75 & P.Value < 0.05) %>% write.table("../Results/DGEA/Filtered_DEGs_tables/High_OS_vs_Low_OS_Verhaak.tsv", sep = "\t", col.names = NA)
```

```{r}
mIDH1_vs_wtIDH_Verhaak_volcanoplots <- mIDH1_vs_wtIDH_Verhaak %>% EnhancedVolcano(lab = rownames(mIDH1_vs_wtIDH_Verhaak), 
                                           x = "logFC", y = "P.Value",
                                           FCcutoff = 0.75, pCutoff = 0.05, 
                                           title = "mIDH1_vs_wtIDH_Verhaak", shape = 1)

mIDH2_vs_wtIDH_Verhaak_volcanoplots <- mIDH2_vs_wtIDH_Verhaak %>% EnhancedVolcano(lab = rownames(mIDH2_vs_wtIDH_Verhaak), 
                                           x = "logFC", y = "P.Value",
                                           FCcutoff = 0.75, pCutoff = 0.05, 
                                           title = "mIDH2_vs_wtIDH_Verhaak", shape = 1)

mIDH1_vs_mIDH2_Verhaak_volcanoplots <- mIDH1_vs_mIDH2_Verhaak %>% EnhancedVolcano(lab = rownames(mIDH1_vs_mIDH2_Verhaak), 
                                           x = "logFC", y = "P.Value",
                                           FCcutoff = 0.75, pCutoff = 0.05, 
                                           title = "mIDH1_vs_mIDH2_Verhaak", shape = 1)

High_OS_vs_Low_OS_Verhaak_volcanoplots <- High_OS_vs_Low_OS_Verhaak %>% EnhancedVolcano(lab = rownames(High_OS_vs_Low_OS_Verhaak), 
                                              x = "logFC", y = "P.Value",
                                              FCcutoff = 0.75, pCutoff = 0.05, 
                                              title = "High_OS_vs_Low_OS_Verhaak", shape = 1)
mIDH1_vs_wtIDH_Verhaak_volcanoplots
mIDH2_vs_wtIDH_Verhaak_volcanoplots
mIDH1_vs_mIDH2_Verhaak_volcanoplots
High_OS_vs_Low_OS_Verhaak_volcanoplots
ggsave("../Results/DGEA/Volcanoplots_mIDH1_vs_wtIDH_Verhaak.png", mIDH1_vs_wtIDH_Verhaak_volcanoplots)
ggsave("../Results/DGEA/Volcanoplots_mIDH2_vs_wtIDH_Verhaak.png", mIDH2_vs_wtIDH_Verhaak_volcanoplots)
ggsave("../Results/DGEA/Volcanoplots_mIDH1_vs_mIDH2_Verhaak.png", mIDH1_vs_mIDH2_Verhaak_volcanoplots)
ggsave("../Results/DGEA/Volcanoplots_High_OS_vs_Low_OS_Verhaak.png", High_OS_vs_Low_OS_Verhaak_volcanoplots)

png2 <- grid.arrange(mIDH1_vs_wtIDH_Verhaak_volcanoplots,
                                mIDH2_vs_wtIDH_Verhaak_volcanoplots,
                                mIDH1_vs_mIDH2_Verhaak_volcanoplots,
                                High_OS_vs_Low_OS_Verhaak_volcanoplots,
                           ncol=2, nrow = 2, top = textGrob('Differential gene expression',just = c('center'),gp = gpar(fontsize = 8)))
png2
ggsave("../Results/DGEA/Volcanoplots_Verhaak.png", png2, height = 1080, width = 1920, units = "px")
```

